/*
 * داده‌های Mock فلش‌کارت تپش + قرارداد دقیق شکل داده (همان قرارداد Backend آینده).
 *
 * موجودیت‌ها:
 *   Deck           { id, userId|null, title, description, type: user|tapesh, visibility,
 *                    subjectId, level, cover, cardCount, createdAt, updatedAt }
 *   Flashcard      { id, deckId, type: basic|basic-hint|cloze|mcq, front, back, hint,
 *                    media, tags[], subjectId, topicId, source, language, status,
 *                    version, createdAt, updatedAt }
 *   UserCardState  { userId, cardId, state, dueAt, lastReviewedAt, reviewCount, lapseCount,
 *                    correctCount, incorrectCount, easeFactor, stability, difficulty,
 *                    intervalMinutes, learningStep, suspended, buriedUntil, bookmarked,
 *                    masteryScore, updatedAt }   ← وضعیت یادگیری متعلق به کاربر است نه کارت
 *   ReviewLog      { id, userId, cardId, deckId, rating, previousState, newState,
 *                    previousInterval, newInterval, timeSpent, reviewedAt, algorithmVersion, mode }
 *   CardSource     { sourceType: lesson|question|article|book|manual|ai|user, sourceId, title, url }
 */

/* رنگ‌های کاور دک — فقط از پالت فعلی تپش */
export const DECK_COLORS = ['#5b8cc7', '#937fcd', '#e26d6d', '#e0b45c', '#77b787', '#ab8e7c', '#ef9196', '#9ed3ab'];

export const SUBJECTS = [
  { id: 'physiology', title: 'فیزیولوژی' },
  { id: 'anatomy', title: 'آناتومی' },
  { id: 'biochemistry', title: 'بیوشیمی' },
  { id: 'pharmacology', title: 'داروشناسی' },
  { id: 'microbiology', title: 'میکروب‌شناسی' },
  { id: 'immunology', title: 'ایمنی‌شناسی' },
  { id: 'pathology', title: 'پاتولوژی' },
  { id: 'general', title: 'عمومی' },
];

/* ── دک‌های رسمی تپش ── */

export const TAPESH_DECKS = [
  {
    id: 'deck-physio-heart',
    userId: null,
    title: 'فیزیولوژی قلب و گردش خون',
    description: 'چرخه قلبی، الکتروفیزیولوژی، تنظیم برون‌ده قلبی و فشار خون — با تمرکز بر High Yield های آزمون.',
    type: 'tapesh',
    visibility: 'public',
    subjectId: 'physiology',
    level: 'علوم پایه',
    cover: '#e26d6d',
    byTapesh: true,
    updatedAt: '2026-09-05T10:00:00.000Z',
  },
  {
    id: 'deck-anatomy-neuro',
    userId: null,
    title: 'آناتومی سیستم عصبی',
    description: 'ساختار مغز، ساقه مغز، راه‌های طولی و اعصاب مغزی به زبان ساده.',
    type: 'tapesh',
    visibility: 'public',
    subjectId: 'anatomy',
    level: 'علوم پایه',
    cover: '#937fcd',
    byTapesh: true,
    updatedAt: '2026-08-28T10:00:00.000Z',
  },
  {
    id: 'deck-pharm-basic',
    userId: null,
    title: 'داروشناسی پایه',
    description: 'فارماکوکینتیک، اتورسپشن و مهم‌ترین داروهای سیستم قلبی-عروقی و عصبی.',
    type: 'tapesh',
    visibility: 'public',
    subjectId: 'pharmacology',
    level: 'علوم پایه',
    cover: '#77b787',
    byTapesh: true,
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'deck-biochem-metab',
    userId: null,
    title: 'بیوشیمی متابولیسم',
    description: 'گلیکولیز، چرخه کربس، انتقال الکترون و تنظیم هورمونی متابولیسم.',
    type: 'tapesh',
    visibility: 'public',
    subjectId: 'biochemistry',
    level: 'علوم پایه',
    cover: '#e0b45c',
    byTapesh: true,
    updatedAt: '2026-08-20T10:00:00.000Z',
  },
  {
    id: 'deck-immuno-basic',
    userId: null,
    title: 'ایمنی‌شناسی پایه',
    description: 'ایمنی ذاتی و اکتسابی، آنتی‌بادی‌ها، کمپلکان و هایپرسنسیتیویتی.',
    type: 'tapesh',
    visibility: 'public',
    subjectId: 'immunology',
    level: 'علوم پایه',
    cover: '#5b8cc7',
    byTapesh: true,
    updatedAt: '2026-08-15T10:00:00.000Z',
  },
  {
    id: 'deck-highyield-basic',
    userId: null,
    title: 'High Yield علوم پایه',
    description: 'نکات طلایی و پرتکرار همه درس‌های علوم پایه — گلچین‌شده توسط تیم آموزشی تپش.',
    type: 'tapesh',
    visibility: 'public',
    subjectId: 'general',
    level: 'ویژه',
    cover: '#ab8e7c',
    byTapesh: true,
    updatedAt: '2026-09-10T10:00:00.000Z',
  },
  {
    id: 'deck-cram-physio',
    userId: null,
    title: 'مرور شب امتحان فیزیولوژی',
    description: 'فشرده‌ترین نکات فیزیولوژی برای مرور سریع شبانه؛ مناسب تکرار چندباره.',
    type: 'tapesh',
    visibility: 'public',
    subjectId: 'physiology',
    level: 'ویژه',
    cover: '#ef9196',
    byTapesh: true,
    updatedAt: '2026-09-11T10:00:00.000Z',
  },
  {
    id: 'deck-micro-basic',
    userId: null,
    title: 'میکروب‌شناسی باکتری‌ها',
    description: 'باکتری‌های مهم گرم مثبت و منفی، توکسین‌ها و درمان‌های کلیدی.',
    type: 'tapesh',
    visibility: 'public',
    subjectId: 'microbiology',
    level: 'علوم پایه',
    cover: '#9ed3ab',
    byTapesh: true,
    updatedAt: '2026-07-30T10:00:00.000Z',
  },
];

const mk = (id, deckId, fields) => ({
  id,
  deckId,
  type: 'basic',
  front: '',
  back: '',
  hint: null,
  media: null,
  tags: [],
  subjectId: null,
  topicId: null,
  source: null,
  language: 'fa',
  status: 'active',
  version: 1,
  createdAt: '2026-08-01T10:00:00.000Z',
  updatedAt: '2026-08-01T10:00:00.000Z',
  ...fields,
});

/* ── کارت‌های دک‌های رسمی ── */

export const TAPESH_CARDS = [
  /* فیزیولوژی قلب */
  mk('c-ph-001', 'deck-physio-heart', {
    type: 'basic',
    front: 'مهم‌ترین تنظیم‌کننده ضربان قلب در حالت استراحت چیست؟',
    back: 'فعالیت پاراسمپاتیک از طریق عصب واگ (Vagus) — با آزادسازی استیل‌کولین روی گره‌های SA و AV.',
    tags: ['قلب', 'فیزیولوژی', 'HighYield'],
    subjectId: 'physiology',
    topicId: 'cardiac-electrophysiology',
    source: { sourceType: 'lesson', sourceId: 'lesson-physio-cardiac-3', title: 'درسنامه فیزیولوژی قلب تپش — بخش ۳', url: null },
  }),
  mk('c-ph-002', 'deck-physio-heart', {
    type: 'cloze',
    front: 'قلب توسط {{c1::گره سینوسی (SA)}} تحریک می‌شود و_impuls از طریق {{c2::گره دهلیزی-بطنی (AV)}} به بطن‌ها می‌رسد.',
    back: 'گره سینوسی پیس‌میکر اصلی است (۶۰–۱۰۰ ضربان)؛ تأخیر در گره AV اجازه پر شدن بطن‌ها را می‌دهد.',
    tags: ['قلب', 'الکتروفیزیولوژی'],
    subjectId: 'physiology',
    topicId: 'cardiac-electrophysiology',
  }),
  mk('c-ph-003', 'deck-physio-heart', {
    type: 'mcq',
    front: 'در فاز صفر پتانسیل عمل سلول عضلانی قلبی، کدام جریان یونی غالب است؟',
    back: 'جریان ورودی Ca²⁺ از کانال‌های نوع L — برخلاف نورون که جریان Na⁺ دارد.',
    options: [
      { text: 'ورود Na⁺ سریع', correct: false },
      { text: 'ورود Ca²⁺ از کانال نوع L', correct: true },
      { text: 'خروج K⁺', correct: false },
      { text: 'ورود Cl⁻', correct: false },
    ],
    explanation: 'سلول‌های عضلانی قلبی نقطه اوج (نوسازی) با جریان Ca²⁺ نوع L ایجاد می‌کنند؛ Na⁺ فقط در عضلات اسکلتی و نورون نقش فاز صفر دارد.',
    tags: ['قلب', 'پتانسیل عمل'],
    subjectId: 'physiology',
    topicId: 'cardiac-electrophysiology',
  }),
  mk('c-ph-004', 'deck-physio-heart', {
    type: 'basic',
    front: 'مکانیسم فرانک-استارلینگ را در یک جمله توضیح بده.',
    back: 'با افزایش حجم پایان دیاستولی (پیش‌بار)، طول سارکومر به سمت طول بهینه می‌رود و نیروی انقباض و برون‌ده قلبی افزایش می‌یابد.',
    hint: 'رابطه پیش‌بار و بازده انقباض',
    tags: ['قلب', 'HighYield'],
    subjectId: 'physiology',
    topicId: 'cardiac-output',
    source: { sourceType: 'book', sourceId: 'guyton-ch9', title: 'کتاب Guyton — فصل ۹', url: null },
  }),
  mk('c-ph-005', 'deck-physio-heart', {
    type: 'cloze',
    front: 'برون‌ده قلبی حاصل‌ضرب {{c1::حجم ضربه‌ای}} در {{c2::ضربان قلب}} است و به‌طور نرمال حدود {{c3::۵ لیتر در دقیقه}} برآورد می‌شود.',
    back: 'CO = SV × HR؛ در بزرگسال ۷۰ ضربان × ۷۰ میلی‌لیتر ≈ ۵ L/min.',
    tags: ['قلب'],
    subjectId: 'physiology',
    topicId: 'cardiac-output',
  }),
  mk('c-ph-006', 'deck-physio-heart', {
    type: 'basic',
    front: 'تفاوت صدای قلبی S1 و S2 چیست و از چه رویدادی ناشی می‌شود؟',
    back: 'S1 (بلندتر، اپکس) از بسته‌شدن دریچه‌های میترال و تریکاسپید در شروع سیستول؛ S2 از بسته‌شدن دریچه‌های آئورت و پولمونر در پایان سیستول.',
    tags: ['قلب', 'صداها'],
    subjectId: 'physiology',
    topicId: 'cardiac-cycle',
  }),
  mk('c-ph-007', 'deck-physio-heart', {
    type: 'basic',
    front: 'در موج ECG، معرف هر جزء چیست: P، QRS، T؟',
    back: 'P: دپلاریزاسیون دهلیز — QRS: دپلاریزاسیون بطن — T: رپلاریزاسیون بطن (رپلاریزاسیون دهلیز در QRS پنهان است).',
    tags: ['قلب', 'ECG', 'HighYield'],
    subjectId: 'physiology',
    topicId: 'cardiac-electrophysiology',
    source: { sourceType: 'lesson', sourceId: 'lesson-physio-ecg-1', title: 'درسنامه ECG تپش — بخش ۱', url: null },
  }),
  mk('c-ph-008', 'deck-physio-heart', {
    type: 'basic',
    front: 'چگونه فشار خون شریانی میان‌مدت تنظیم می‌شود؟ (سیستم اصلی)',
    back: 'سیستم رنین-آنژیوتانسین-آلدوسترون (RAAS): آنژیوتانسین II هم وازوکانستریکشن ایجاد می‌کند هم آلدوسترون و احتباس آب و سدیم را افزایش می‌دهد.',
    tags: ['قلب', 'فشار خون', 'HighYield'],
    subjectId: 'physiology',
    topicId: 'blood-pressure',
  }),
  mk('c-ph-009', 'deck-physio-heart', {
    type: 'mcq',
    front: 'کدام مورد افزایش فشار داخل قفسه سینه را به کاهش برون‌ده قلبی می‌رساند؟',
    back: 'افزایش پیش‌بار ریوی با کاهش برگشت وریدی (Preload) به قلب راست همراه است؛ در Valsalva برگشت وریدی کاهش می‌یابد و برون‌ده افت می‌کند.',
    options: [
      { text: 'Valsalva (فاز نگه‌داشتن)', correct: true },
      { text: 'بلند شدن از حالت خوابیده', correct: false },
      { text: 'انقباض عضلات پا', correct: false },
      { text: 'دم عمیق عادی', correct: false },
    ],
    explanation: 'در مانور Valsalva فشار داخل قفسه سینه بالا می‌رود، برگشت وریدی کم می‌شود و در نتیجه Preload و برون‌ده قلبی افت می‌کند.',
    tags: ['قلب', 'کلینیکال'],
    subjectId: 'physiology',
    topicId: 'cardiac-output',
  }),
  mk('c-ph-010', 'deck-physio-heart', {
    type: 'basic',
    front: 'نقش گیرنده‌های کشش (Baroreceptors) در تنظیم فشار لحظه‌ای چیست؟',
    back: 'در کمان آئورت و سینوس کاروتید قرار دارند؛ افزایش فشار → سیگنال بیشتر از طریق عصب گلاسوفارنژ و واگ → مهار سمپاتیک و فعال‌سازی پاراسمپاتیک → کاهش ضربان و گشاد شدن عروق.',
    tags: ['قلب', 'فشار خون'],
    subjectId: 'physiology',
    topicId: 'blood-pressure',
  }),
  mk('c-ph-011', 'deck-physio-heart', {
    type: 'cloze',
    front: 'حجم ضربه‌ای به سه عامل بستگی دارد: {{c1::پیش‌بار}}، {{c2::قراردادپذیری}} و {{c3::پس‌بار}}.',
    back: 'Preload (حجم پایان دیاستول)، Contractility و Afterload (مقاومت آئورت) — سه ضلع اصلی تعیین SV.',
    tags: ['قلب'],
    subjectId: 'physiology',
    topicId: 'cardiac-output',
  }),
  mk('c-ph-012', 'deck-physio-heart', {
    type: 'basic',
    front: 'بازگشت وریدی (Venous Return) چگونه به برون‌ده قلبی متصل است؟',
    back: 'در حالت پایدار، بازگشت وریدی = برون‌ده قلبی؛ هر عاملی که برگشت را کم کند (خونریزی، ایستادن طولانی) برون‌ده را کم می‌کند.',
    tags: ['قلب'],
    subjectId: 'physiology',
    topicId: 'cardiac-output',
  }),

  /* آناتومی سیستم عصبی */
  mk('c-an-001', 'deck-anatomy-neuro', {
    type: 'basic',
    front: 'اجزای ساقه مغز (Brainstem) از بالا به پایین کدام‌اند؟',
    back: 'مید‌برین (Midbrain) → پونس (Pons) → مدولا (Medulla Oblongata).',
    tags: ['آناتومی', 'ساقه مغز', 'HighYield'],
    subjectId: 'anatomy',
    topicId: 'brainstem',
  }),
  mk('c-an-002', 'deck-anatomy-neuro', {
    type: 'cloze',
    front: 'مخچه از طریق سه پدونکول به ساقه مغز وصل می‌شود: پدونکول {{c1::زیرین}} به مدولا، {{c2::میانی}} به پونس و {{c3::زبرین}} به مید‌برین.',
    back: 'Inferior → Medulla، Middle → Pons، Superior → Midbrain؛ مسیر خروجی مخچه از پدونکول زبرین است.',
    tags: ['آناتومی', 'مخچه'],
    subjectId: 'anatomy',
    topicId: 'cerebellum',
  }),
  mk('c-an-003', 'deck-anatomy-neuro', {
    type: 'basic',
    front: 'کدام عصب مغزی از پونس خارج می‌شود و نقش حرکتی چشم دارد؟',
    back: 'عصب Abducens (CN VI) — مسئول حرکت جانبی چشم با فعال‌سازی عضله راست جانبی (Lateral Rectus).',
    tags: ['آناتومی', 'اعصاب مغزی'],
    subjectId: 'anatomy',
    topicId: 'cranial-nerves',
  }),
  mk('c-an-004', 'deck-anatomy-neuro', {
    type: 'basic',
    front: 'نقص در شریان مغزی میانی (MCA) چه علائمی ایجاد می‌کند؟',
    back: 'فلج بازو و صورت (برخلاف PCA که پا را درگیر می‌کند)، اختلاف تکلم در سمت چپ و نگاه به سمت ضایعه.',
    tags: ['آناتومی', 'عروق مغز', 'HighYield'],
    subjectId: 'anatomy',
    topicId: 'cerebral-vessels',
    source: { sourceType: 'question', sourceId: 'q-bank-1421', title: 'بانک سؤال بین‌الملل — سؤال ۱۴۲۱', url: null },
  }),
  mk('c-an-005', 'deck-anatomy-neuro', {
    type: 'cloze',
    front: 'بطن‌های مغزی شامل دو بطن {{c1::جانبی}}، بطن {{c2::سوم}} در تالاموس و بطن {{c3::چهارم}} بین پونس و مخچه هستند.',
    back: 'CSF از شبکه‌های کروئید بطن‌های جانبی تولید و از سوراخ‌های مگندی و لوشکا در بطن چهارم به فضای ساب‌آراکنوئید می‌ریزد.',
    tags: ['آناتومی', 'CSF'],
    subjectId: 'anatomy',
    topicId: 'ventricles',
  }),
  mk('c-an-006', 'deck-anatomy-neuro', {
    type: 'basic',
    front: 'آسیب عصب Hypoglossal (CN XII) چه علامتی می‌دهد؟',
    back: 'انحراف زبان به سمت ضایعه هنگام برون‌روی؛ عضله گنیوگلوسوس سمت سالم زبان را به سمت نیمه فلج می‌راند.',
    tags: ['آناتومی', 'اعصاب مغزی'],
    subjectId: 'anatomy',
    topicId: 'cranial-nerves',
  }),

  /* داروشناسی پایه */
  mk('c-fa-001', 'deck-pharm-basic', {
    type: 'basic',
    front: 'چهار فرایند اصلی فارماکوکینتیک کدام‌اند؟',
    back: 'Absorption (جذب)، Distribution (توزیع)، Metabolism (متابولیسم) و Excretion (دفع) — ADME.',
    tags: ['داروشناسی', 'فارماکوکینتیک'],
    subjectId: 'pharmacology',
    topicId: 'pharmacokinetics',
  }),
  mk('c-fa-002', 'deck-pharm-basic', {
    type: 'cloze',
    front: 'داروهای اول عبور از متابولیسم کبدی با اثر کاهش‌یافته، در اصطلاح اثر {{c1::First-pass}} دارند؛ نمونه بارز آن {{c2::نیتروگلیسیرین زیرزبانی}} است.',
    back: 'فرار First-pass: مصرف زیرزبانی/رکتال یا تزریقی از متابولیسم کبدی عبور می‌کند؛ خوراکی نیتروگلیسیرین تقریباً بی‌اثر است.',
    tags: ['داروشناسی', 'HighYield'],
    subjectId: 'pharmacology',
    topicId: 'pharmacokinetics',
  }),
  mk('c-fa-003', 'deck-pharm-basic', {
    type: 'mcq',
    front: 'مکانیسم اصلی اثر دیگوکسین چیست؟',
    back: 'مهار پمپ Na⁺/K⁺-ATPase → افزایش Ca²⁺ داخل سلولی → افزایش انقباض (اینوتروپی مثبت).',
    options: [
      { text: 'مهار بتا-۱', correct: false },
      { text: 'مهار Na⁺/K⁺-ATPase', correct: true },
      { text: 'مهار کانال کلسیم', correct: false },
      { text: 'مهار ACE', correct: false },
    ],
    explanation: 'مهار پمپ سدیم-پتاسیم باعث تجمع سدیم داخل سلولی و کاهش خروج Ca²⁺ از طریق مبادله‌گر Na/Ca می‌شود؛ در نتیجه ذخیره کلسیم و نیروی انقباض بالا می‌رود.',
    tags: ['داروشناسی', 'قلب'],
    subjectId: 'pharmacology',
    topicId: 'cardiovascular-drugs',
  }),
  mk('c-fa-004', 'deck-pharm-basic', {
    type: 'basic',
    front: 'تفاوت داروهای آنتاگونیست و پارت آنتاگونیست چیست؟',
    back: 'آنتاگونیست کامل در حضور لیگاند اثر بیولوژیک ایجاد نمی‌کند؛ پارت آنتاگونیست اثر ضعیف‌تری از لیگاند کامل دارد و هم‌زمان مانع اثر آن می‌شود.',
    tags: ['داروشناسی', 'اتورسپشن'],
    subjectId: 'pharmacology',
    topicId: 'pharmacodynamics',
  }),
  mk('c-fa-005', 'deck-pharm-basic', {
    type: 'basic',
    front: 'نیمه‌عمق مفید (Half-life) چگونه به دوز ثابت (Steady state) مرتبط است؟',
    back: 'حدود ۴–۵ نیمه‌عمق طول می‌کشد تا غلظت به ۹۴–۹۷٪ حالت پایا برسد؛ زمان رسیدن به Steady state مستقل از دوز است.',
    tags: ['داروشناسی', 'فارماکوکینتیک'],
    subjectId: 'pharmacology',
    topicId: 'pharmacokinetics',
    source: { sourceType: 'book', sourceId: 'katzung-ch3', title: 'کتاب Katzung — فصل ۳', url: null },
  }),
  mk('c-fa-006', 'deck-pharm-basic', {
    type: 'cloze',
    front: 'آسپرین با {{c1::مهار غیرقابل برگشت آنزیم COX-1}} اثر ضدپلاکت خود را نشان می‌دهد و به همین دلیل اثر آن تا {{c2::عمر پلاکت (۷-۱۰ روز)}} باقی می‌ماند.',
    back: 'پلاکت هسته ندارند و COX جدید نمی‌سازند؛ با هر دوز آسپرین باید تا بازسازی پلاکت‌ها صبر کرد.',
    tags: ['داروشناسی', 'خون'],
    subjectId: 'pharmacology',
    topicId: 'cardiovascular-drugs',
  }),
  mk('c-fa-007', 'deck-pharm-basic', {
    type: 'basic',
    front: 'عوارض اصلی مهارکننده‌های ACE را نام ببرید.',
    back: 'سرفه خشک (تجمع برادی‌کینین)، هایپرکالمی، افزایش کراتینین در تنگی دوطرفه شریان رینال، آنژیوادم (نادر).',
    tags: ['داروشناسی', 'قلب', 'HighYield'],
    subjectId: 'pharmacology',
    topicId: 'cardiovascular-drugs',
  }),
  mk('c-fa-008', 'deck-pharm-basic', {
    type: 'mcq',
    front: 'کدام دارو در آسم به‌عنوان داروی کنترل‌کننده بلندمدت نگه‌دارنده است؟',
    back: 'کورتیکواستروئید استنشاقی (مثل بودسونید) — داروی پایه کنترل آسم؛ بتا-۲ آگونیست بلند اثر (سالمترول) همیشه همراه آن است.',
    options: [
      { text: 'سالبتامول استنشاقی', correct: false },
      { text: 'کورتیکواستروئید استنشاقی', correct: true },
      { text: 'ایپراتروپیوم', correct: false },
      { text: 'تئوفیلین خوراکی', correct: false },
    ],
    explanation: 'ICS پایه درمان کنترل آسم است؛ سالبتامول فقط رهایی‌بخش (Rescue) است.',
    tags: ['داروشناسی', 'تنفس'],
    subjectId: 'pharmacology',
    topicId: 'respiratory-drugs',
  }),

  /* بیوشیمی متابولیسم */
  mk('c-bi-001', 'deck-biochem-metab', {
    type: 'basic',
    front: 'مرحله نرخ-تعیین‌کننده گلیکولیز کدام است و چه آنزیمی آن را کاتالیز می‌کند؟',
    back: 'تبدیل فروکتوز-۶-فسفات به فروکتوز-۱،۶-بیس‌فسفات توسط فسفوفروکتوکیناز-۱ (PFK-1) — فعال‌شده با AMP و فروکتوز-۲،۶-بیس‌فسفات، مهارشده با ATP و سیترات.',
    tags: ['بیوشیمی', 'گلیکولیز', 'HighYield'],
    subjectId: 'biochemistry',
    topicId: 'glycolysis',
  }),
  mk('c-bi-002', 'deck-biochem-metab', {
    type: 'cloze',
    front: 'در چرخه کربس، هر استیل-کوآ منجر به تولید {{c1::۳}} NADH، {{c2::۱}} FADH₂ و {{c3::۱}} GTP می‌شود.',
    back: 'مجموع ATP معادل هر استیل-کوآ ≈ ۱۰ ATP (۳NADH×۲.۵ + ۱FADH₂×۱.۵ + ۱GTP).',
    tags: ['بیوشیمی', 'چرخه کربس'],
    subjectId: 'biochemistry',
    topicId: 'tca-cycle',
  }),
  mk('c-bi-003', 'deck-biochem-metab', {
    type: 'basic',
    front: 'نقش انسولین و گلوکاگون در نسبت فسفوریلاسیون PFK-2 چیست؟',
    back: 'انسولین با فعال‌سازی فسفوپروتئین فسفاتاز، PFK-2 را دفسفوریلاسیون می‌کند → فروکتوز-۲،۶-بیس‌فسفات ↑ → گلیکولیز فعال. گلوکاگون برعکس و گلیکولیز را مهار و گلوکونئوژنز را فعال می‌کند.',
    tags: ['بیوشیمی', 'هورمون'],
    subjectId: 'biochemistry',
    topicId: 'metabolic-regulation',
  }),
  mk('c-bi-004', 'deck-biochem-metab', {
    type: 'basic',
    front: 'کبد از کدام مسیر قادر است گلوکز را از لاکتات و آلانین بسازد؟',
    back: 'گلوکونئوژنز — عمدتاً در کبد؛ از پیرووات با عبور از میتوکندری (پیرووات کربوکسیلاز) شروع می‌شود.',
    tags: ['بیوشیمی'],
    subjectId: 'biochemistry',
    topicId: 'gluconeogenesis',
  }),
  mk('c-bi-005', 'deck-biochem-metab', {
    type: 'mcq',
    front: 'کمپلکس‌های I تا IV زنجیره انتقال الکترون، پروتون را به کدام فضا پمپ می‌کنند؟',
    back: 'از ماتریکس میتوکندری به فضای بین غشایی — گرادیان پروتونی موتور ATP سنتاز است.',
    options: [
      { text: 'از سیتوزول به ماتریکس', correct: false },
      { text: 'از ماتریکس به فضای بین غشایی', correct: true },
      { text: 'از فضای بین غشایی به ماتریکس', correct: false },
      { text: 'پمپ پروتونی ندارند', correct: false },
    ],
    explanation: 'کمپلکس I، III و IV پمپ پروتون انجام می‌دهند؛ جهت همیشه به فضای بین غشایی است (درون-به-بیرون).',
    tags: ['بیوشیمی', 'انتقال الکترون'],
    subjectId: 'biochemistry',
    topicId: 'etc',
  }),
  mk('c-bi-006', 'deck-biochem-metab', {
    type: 'cloze',
    front: 'آنزیم {{c1::گلیکوژن فسفوریلاز}} گلیکوژن را به {{c2::گلوکز-۱-فسفات}} تجزیه می‌کند و با فعال‌سازی توسط {{c3::PKA}} تحت کنترل گلوکاگون است.',
    back: 'زنجیره: گلوکاگون → cAMP ↑ → PKA → فسفوریلاز کیناز → فسفوریلاز فعال.',
    tags: ['بیوشیمی', 'گلیکوژن'],
    subjectId: 'biochemistry',
    topicId: 'glycogen',
  }),

  /* ایمنی‌شناسی */
  mk('c-im-001', 'deck-immuno-basic', {
    type: 'basic',
    front: 'تفاوت ایمنی ذاتی و اکتسابی در دو محور اصلی چیست؟',
    back: 'ذاتی: سریع (ساعت‌ها)، غیراختصاصی، حافظه ندارد (نوتروفیل، ماکروفاژ، کمپلکان، باری‌ر). اکتسابی: کند (روزها)، اختصاصی، حافظه قوی دارد (لنفوسیت B و T).',
    tags: ['ایمنی‌شناسی', 'HighYield'],
    subjectId: 'immunology',
    topicId: 'innate-vs-adaptive',
  }),
  mk('c-im-002', 'deck-immuno-basic', {
    type: 'cloze',
    front: 'آنتی‌بادی IgG تنها آنتی‌بادی است که از {{c1::جفت}} عبور می‌کند و IgA عمدتاً در {{c2::ترشحات مخاطی}} یافت می‌شود.',
    back: 'IgG با گیرنده FcRn از جفت عبور و ایمنی نوزاد را فراهم می‌کند؛ IgA دیمری و در شیر مادر و مخاط‌ها است.',
    tags: ['ایمنی‌شناسی', 'آنتی‌بادی'],
    subjectId: 'immunology',
    topicId: 'antibodies',
  }),
  mk('c-im-003', 'deck-immuno-basic', {
    type: 'mcq',
    front: 'هایپرسنسیتیویتی نوع I توسط کدام مکانیسم ایجاد می‌شود؟',
    back: 'IgE و دگرانولاسیون ماست‌سل — آنافیلاکسی و آلرژی فوری.',
    options: [
      { text: 'IgG و کمپلکان', correct: false },
      { text: 'IgE و ماست‌سل', correct: true },
      { text: 'کمپلکس ایمن', correct: false },
      { text: 'لنفوسیت T سیتوتوکسیک', correct: false },
    ],
    explanation: 'نوع I: IgE/ماست‌سل — نوع II: IgG/IgM علیه سلول — نوع III: کمپلکس ایمن — نوع IV: تأخیری T-cell.',
    tags: ['ایمنی‌شناسی', 'هایپرسنسیتیویتی'],
    subjectId: 'immunology',
    topicId: 'hypersensitivity',
  }),
  mk('c-im-004', 'deck-immuno-basic', {
    type: 'basic',
    front: 'نقش MHC کلاس I و II در ارائه آنتی‌ژن چه تفاوتی دارد؟',
    back: 'MHC I: آنتی‌ژن درون‌زا به CD8+ (همه سلول‌های نوکلئاته). MHC II: آنتی‌ژن برون‌زا به CD4+ (فقط APC مثل ماکروفاژ، دندریتیک، B).',
    tags: ['ایمنی‌شناسی', 'MHC', 'HighYield'],
    subjectId: 'immunology',
    topicId: 'antigen-presentation',
  }),
  mk('c-im-005', 'deck-immuno-basic', {
    type: 'cloze',
    front: 'در مسیر کلاسیک کمپلکان، {{c1::IgM یا IgG}} متصل‌شده به آنتی‌ژن فعال‌سازی را آغاز می‌کند و C3 convertase آن ترکیب {{c2::C4b2a}} است.',
    back: 'مسیر لکتینی و آلترنیت مستقل از آنتی‌بادی فعال می‌شوند؛ خروجی مشترک هر سه مسیر C3b و MAC است.',
    tags: ['ایمنی‌شناسی', 'کمپلکان'],
    subjectId: 'immunology',
    topicId: 'complement',
  }),

  /* High Yield علوم پایه */
  mk('c-hy-001', 'deck-highyield-basic', {
    type: 'basic',
    front: 'اولین اقدام در احیای بیمار با افت فشار شدید و نبض تپنده چیست؟ (اصل عمومی)',
    back: 'ABC — Airway, Breathing, Circulation؛ در فشار پایین، دسترسی وریدی و تزریق سریع مایع (Fluid resuscitation) قبل از هر دارو.',
    tags: ['HighYield', 'کلینیکال'],
    subjectId: 'general',
    topicId: 'clinical-principles',
  }),
  mk('c-hy-002', 'deck-highyield-basic', {
    type: 'basic',
    front: 'شایع‌ترین علت نارسایی حاد کلیوی در بیمارستان چیست؟',
    back: 'نکروز توبولی حاد (ATN) — عمدتاً ایسکمی ناشی از افت فشار طولانی و یا نفروتوکسین‌ها.',
    tags: ['HighYield', 'کلیه'],
    subjectId: 'general',
    topicId: 'renal',
    source: { sourceType: 'article', sourceId: 'art-akm-22', title: 'مقاله تپش — نارسایی کلیوی', url: null },
  }),
  mk('c-hy-003', 'deck-highyield-basic', {
    type: 'cloze',
    front: 'در اسیدوز متابولیک، جبران تنفسی باعث {{c1::کاهش}} PCO₂ می‌شود؛ فرمول وینتر: {{c2::PCO₂ = 1.5 × HCO₃⁻ + 8 (±2)}}.',
    back: 'اگر PCO₂ اندازه‌گیری‌شده از مقدار محاسباتی دور باشد، اختلال تنفسی ترکیبی وجود دارد.',
    tags: ['HighYield', 'ABG'],
    subjectId: 'general',
    topicId: 'acid-base',
  }),
  mk('c-hy-004', 'deck-highyield-basic', {
    type: 'mcq',
    front: 'بیمار با اسهال آبکی شدید؛ انتظار داریم اسید-پایه چه باشد؟',
    back: 'اسیدوز متابولیک با آنیون‌گپ نرمال (هایپرکلورمیک) — از دست رفتن بیکربنات با اسهال.',
    options: [
      { text: 'آلکالوز متابولیک', correct: false },
      { text: 'اسیدوز متابولیک با آنیون‌گپ بالا', correct: false },
      { text: 'اسیدوز متابولیک با آنیون‌گپ نرمال', correct: true },
      { text: 'اسیدوز تنفسی', correct: false },
    ],
    explanation: 'اسهال = از دست رفتن HCO₃⁻؛ کلر جبران می‌شود و آنیون‌گپ نرمال می‌ماند.',
    tags: ['HighYield', 'ABG'],
    subjectId: 'general',
    topicId: 'acid-base',
  }),
  mk('c-hy-005', 'deck-highyield-basic', {
    type: 'basic',
    front: 'چهار نکته کلیدی در شناسایی سندرم‌های High Yield قلبی-عروقی؟',
    back: 'MI (درد >۲۰ دقیقه + CK-MB/Troponin)، آنژین ناپایدار (درد بدون آنزیم)، پریکاردیت (درد با تغییر وضعیت + فریکشن راب)، آئورت دیسکشن (درد تیز کشیده‌شونده به پشت).',
    tags: ['HighYield', 'قلب'],
    subjectId: 'general',
    topicId: 'cardiovascular',
  }),
  mk('c-hy-006', 'deck-highyield-basic', {
    type: 'basic',
    front: 'مکانیسم مقاومت به انسولین در دیابت نوع ۲ در سطح گیرنده چیست؟',
    back: 'کاهش فسفوریلاسیون گیرنده انسولین و مسیر PI3K/AKT — نه کاهش تعداد گیرنده؛ به همین دلیل IRS-1 و انتقال GLUT4 مختل می‌شود.',
    tags: ['HighYield', 'اندوکرین'],
    subjectId: 'general',
    topicId: 'endocrine',
  }),

  /* مرور شب امتحان فیزیولوژی */
  mk('c-cr-001', 'deck-cram-physio', {
    type: 'basic',
    front: '۵ نکته یک‌خطی درباره گره SA؟',
    back: 'پیس‌میکر اصلی — پتانسیل آهسته (I_f funny channel) — نرخ ۶۰-۱۰۰ — آپ‌استروک Ca²⁺ (T-type) — تحت تأثیر واگ/سمپاتیک.',
    tags: ['مرور سریع', 'قلب'],
    subjectId: 'physiology',
    topicId: 'cardiac-electrophysiology',
  }),
  mk('c-cr-002', 'deck-cram-physio', {
    type: 'cloze',
    front: 'فازهای پتانسیل عمل بطنی: صفر = {{c1::Na⁺}}، یک = {{c2::K⁺ گذرا}}، دو = {{c3::Ca²⁺}}، سه = {{c4::K⁺}}، چهار = {{c5::Na/K ATPase}}.',
    back: 'پلاتو (فاز ۲) ویژگی اختصاصی قلب است و فرصت ریفرکتوری مطلق را می‌دهد (جلوگیری از تیتانی).',
    tags: ['مرور سریع', 'ECG'],
    subjectId: 'physiology',
    topicId: 'cardiac-electrophysiology',
  }),
  mk('c-cr-003', 'deck-cram-physio', {
    type: 'basic',
    front: 'تفاوت پیش‌بار و پس‌بار در یک جمله + نمونه بالینی؟',
    back: 'پیش‌بار = کشش اولیه قبل از انقباض (حجم پایان دیاستول)؛ پس‌بار = مقاومت مقابل تخلیه (فشار آئورت). نمونه: انفوزیون مایع پیش‌بار را بالا می‌برد؛ تنگی آئورت پس‌بار را.',
    tags: ['مرور سریع', 'قلب'],
    subjectId: 'physiology',
    topicId: 'cardiac-output',
  }),
  mk('c-cr-004', 'deck-cram-physio', {
    type: 'basic',
    front: 'در ECG، کدام فاصله نشان‌دهنده هدایت AV است؟ نرمالش چند است؟',
    back: 'فاصله PR — نرمال ۰.۱۲ تا ۰.۲۰ ثانیه؛ بیشتر = بلوک درجه ۱، کمتر = مسیر جانبی (مثل WPW).',
    tags: ['مرور سریع', 'ECG'],
    subjectId: 'physiology',
    topicId: 'cardiac-electrophysiology',
  }),
  mk('c-cr-005', 'deck-cram-physio', {
    type: 'mcq',
    front: 'ورزش باعث چه تغییری در برون‌ده قلبی می‌شود؟',
    back: 'برون‌ده ۴-۵ برابر می‌شود — هم HR هم SV افزایش می‌یابند (کشش سمپاتیک + پمپ عضلانی + تنفس).',
    options: [
      { text: 'فقط HR زیاد می‌شود', correct: false },
      { text: 'SV کم می‌شود', correct: false },
      { text: 'HR و SV هر دو زیاد می‌شوند', correct: true },
      { text: 'برون‌ده ثابت می‌ماند', correct: false },
    ],
    explanation: 'در ورزش دینامیک: تزریق سمپاتیک + بازگشت وریدی (پمپ عضلانی) = HR↑ و SV↑؛ CO تا ~۲۰ L/min.',
    tags: ['مرور سریع', 'قلب'],
    subjectId: 'physiology',
    topicId: 'cardiac-output',
  }),

  /* میکروب‌شناسی */
  mk('c-mi-001', 'deck-micro-basic', {
    type: 'basic',
    front: 'باکتری گرم-مثبت خوشه‌ای کاتالاز-مثبت و کوالاز-منفی شایع روی پوست؟',
    back: 'استافیلوکوکوس اپیدرمیدیس — پاتوژن فرصت‌طلب در پروتزها و کاتترها (چسبندگی به صفحات پلی‌استیرون).',
    tags: ['میکروب', 'گرم مثبت'],
    subjectId: 'microbiology',
    topicId: 'gram-positive',
  }),
  mk('c-mi-002', 'deck-micro-basic', {
    type: 'cloze',
    front: 'استرپتوکوکوس پنومونیه گرم-{{c1::مثبت}} دیپلوکوکوس {{c2::لنست-شکل}} است و با {{c3::کپسول پلی‌ساکاریدی}} ویرولانس دارد.',
    back: 'کوئلینگ مثبت (تورم کپسولی) و تراست آگلوتیناسیون ابزارهای شناسایی آن‌اند؛ واکسین بر علیه کپسول است.',
    tags: ['میکروب', 'گرم مثبت'],
    subjectId: 'microbiology',
    topicId: 'gram-positive',
  }),
  mk('c-mi-003', 'deck-micro-basic', {
    type: 'basic',
    front: 'توکسین کدام باکتری با مهار releasing factor عامل اسهال آبکی (مثل ریس) است؟',
    back: 'Vibrio cholerae — توکسین کولرا ADP-ریبوزیله Gsα → cAMP ↑ → فعالیت CFTR → دفع کلر و اسهال آبکی (آب-برنجی).',
    tags: ['میکروب', 'توکسین', 'HighYield'],
    subjectId: 'microbiology',
    topicId: 'toxins',
  }),
  mk('c-mi-004', 'deck-micro-basic', {
    type: 'mcq',
    front: 'بیمار با فلج پیش‌رونده بعد از زخم آلوده خاکی؛ تشخیص مظنون؟',
    back: 'تتانوس (Clostridium tetani) — توکسین تانوسپاسمین با جلوگیری از آزادسازی گلیسین و GABA در نخاع اسپاسم ایجاد می‌کند.',
    options: [
      { text: 'بوتولیسم', correct: false },
      { text: 'تتانوس', correct: true },
      { text: 'دیفتری', correct: false },
      { text: 'گنگرن گازی', correct: false },
    ],
    explanation: 'بوتولیسم فلج شل (مهار استیل‌کولین)، تیتانوس اسپاسم (مهار مهارکننده‌ها) — دو قطب مخالف فلج.',
    tags: ['میکروب', 'کلستریدیا'],
    subjectId: 'microbiology',
    topicId: 'toxins',
  }),
  mk('c-mi-005', 'deck-micro-basic', {
    type: 'basic',
    front: 'تفاوت اندوتوکسین و اگزوتوکسین در سه محور؟',
    back: 'اندوتوکسین (LPS دیوار گرمنفی): بخشی از ساختار، پایدار حرارتی، اثر سیستمیک TNF/IL-1. اگزوتوکسین: پروتئین ترشح‌شده، ناپایدار حرارتی، اثر اختصاصی و قوی (معمولاً آنتی‌ژنیک).',
    tags: ['میکروب', 'HighYield'],
    subjectId: 'microbiology',
    topicId: 'toxins',
  }),
];

/* دک پیش‌فرض کاربر تازه‌وارد (نمونه سناریو) */
export const SEED_USER_DECK = {
  id: 'deck-my-mistakes',
  userId: 'me',
  title: 'اشتباهات من',
  description: 'کارت‌های ساخته‌شده از سؤال‌هایی که اشتباه جواب داده‌ام.',
  type: 'user',
  visibility: 'private',
  subjectId: 'general',
  level: null,
  cover: '#5b8cc7',
  byTapesh: false,
  updatedAt: '2026-09-12T10:00:00.000Z',
};

export const SEED_USER_CARDS = [
  mk('c-us-001', 'deck-my-mistakes', {
    type: 'mcq',
    front: 'در انفارکتوس میوکارد، اولین آنزیمی که بالا می‌رود کدام است؟',
    back: 'میوگلوبین (۲ ساعت) اما اختصاصی نیست؛ تروپونین اختصاصی‌ترین است و CK-MB برای ریسک ریسک‌های مجدد (Reinfarction) استفاده می‌شود.',
    options: [
      { text: 'CK-MB', correct: false },
      { text: 'میوگلوبین', correct: true },
      { text: 'تروپونین I', correct: false },
      { text: 'LDH', correct: false },
    ],
    explanation: 'زمان‌بندی: میوگلوبین ۲-۴ ساعت، تروپونین ۳-۱۲ ساعت (می‌ماند تا ۷-۱۰ روز)، CK-MB ۴-۸ ساعت (۲-۳ روز).',
    tags: ['اشتباهات', 'قلب', 'آزمون'],
    subjectId: 'physiology',
    topicId: 'cardiac-output',
    source: { sourceType: 'question', sourceId: 'q-bank-0341', title: 'بانک سؤال بین‌الملل — سؤال ۳۴۱', url: null },
  }),
  mk('c-us-002', 'deck-my-mistakes', {
    type: 'basic',
    front: 'جریان خون ریوی نسبت به گردش سیستمیک چه تفاوتی در مقاومت و فشار دارد؟',
    back: 'مقاومت و فشار ریوی حدود یک‌ششم سیستمیک است — عروق ریوی گشاد و کم‌مقاوم‌اند؛ به همین دلیل فشار خون ریوی نرمال بسیار پایین است.',
    tags: ['اشتباهات', 'قلب'],
    subjectId: 'physiology',
    topicId: 'cardiac-output',
    source: { sourceType: 'question', sourceId: 'q-bank-0512', title: 'بانک سؤال بین‌الملل — سؤال ۵۱۲', url: null },
  }),
  mk('c-us-003', 'deck-my-mistakes', {
    type: 'cloze',
    front: 'کورتیزول با فعال‌سازی {{c1::لیپولیز}} و {{c2::گلوکونئوژنز}} به‌صورت کاتابولیک عمل می‌کند اما در بافت‌های {{c3::کبدی}} اثر آنابولیک گلوکز دارد.',
    back: 'کورتیزول هورمون استرس است: تجزیه پروتئین عضلانی، لیپولیز و حمایت از گلوکونئوژنز؛ اما در کبد افزایش ذخیره گلیکوژن.',
    tags: ['اشتباهات', 'اندوکرین'],
    subjectId: 'biochemistry',
    topicId: 'metabolic-regulation',
    source: { sourceType: 'lesson', sourceId: 'lesson-endo-7', title: 'درسنامه اندوکرین تپش — بخش ۷', url: null },
  }),
];

/* ── پیشنهادهای هوشمند (Smart Suggestions) ──
 * شکل payload با قرارداد آیندهٔ «میک به فلش‌کارت» و «تبدیل سؤال» هماهنگ است.
 */
export const SMART_SUGGESTIONS = [
  {
    id: 'sug-mistakes',
    kind: 'mistakes',
    icon: 'warn',
    title: '۱۲ سؤال داری که بیش از یک بار اشتباه زده‌ای',
    note: 'از این سؤال‌ها فلش‌کارت بساز تا دیگر تکرار نشوند.',
    actionLabel: 'ساخت فلش‌کارت',
    accent: '#ef9196',
  },
  {
    id: 'sug-rewrite',
    kind: 'rewrite',
    icon: 'edit',
    title: '۳ کارت ۳ بار پشت‌سرهم «دوباره» خورده‌اند',
    note: 'شاید متن کارت روشن نیست؛ بازنویسی‌اش کن یا به دو کارت اتمیک تقسیمش کن.',
    actionLabel: 'بازبینی کارت‌ها',
    accent: '#e0b45c',
  },
  {
    id: 'sug-topic',
    kind: 'topic',
    icon: 'spark',
    title: 'مبحث «تنظیم فشار خون» برای فلش‌کارت مناسب است',
    note: 'در این مبحث ۴۸ سؤال حل کرده‌ای اما فقط ۳ کارت داری.',
    actionLabel: 'ساخت کارت از این مبحث',
    accent: '#937fcd',
  },
];

/* ── پیشنهاد کارت AI (قرارداد آینده — فقط پیش‌نمایش و با تأیید کاربر) ── */
export const AI_CARD_PREVIEW = {
  type: 'basic',
  front: 'مکانیسم فرانک-استارلینگ در یک جمله چیست؟',
  back: 'افزایش پیش‌بار (حجم پایان دیاستولی) طول سارکومر را به سمت طول بهینه می‌رساند و نیروی انقباض را بالا می‌برد.',
  disclaimer: 'پیشنهاد هوشمند تپش — قبل از افزودن بازبینی کن.',
};
