/* ── دادهٔ «شبکه دانش» تپش — مدل دانش پزشکی مبتنی بر ارتباط ──
   فلسفه: دانش را بر اساس «ارتباط میان مفاهیم» نشان می‌دهیم، نه فقط درس و فصل.
   مرکز شبکهٔ نمونه «دیابت» است و مفاهیم شش درس اصلی به آن وصل‌اند.

   قرارداد سرویس برای اتصال به بک‌اند در knowledgeService.js مستند شده؛ این فایل فقط داده است.

   ساختار هر Topic (نود):
     id / slug            شناسه پایدار
     title / englishTitle عنوان فارسی و انگلیسی
     type                 disease | concept | anatomy | process | pathway | drug | cell
                          | molecule | microorganism | finding | labTest
     courses[]            درس‌هایی که مفهوم در آن‌ها مطالعه می‌شود (یک مفهوم می‌تواند بین‌درسی باشد)
     description          تعریف کوتاه (۱-۲ جمله)
     whyImportant         چرا مهم است (برای صفحه اختصاصی Topic)
     keywords             کلیدواژه برای جست‌وجو و پل زدن به سایر بخش‌های تپش
     aliases              مترادف‌ها و معادل‌های انگلیسی/عامیانه
     prerequisites[]      مفاهیمی که باید قبل از این مفهوم فهمیده شوند (پایهٔ Learning Path)
     importance           ۱ تا ۵ (مقیاس اهمیت آزمونی/بالینی)
     difficulty           پایه | متوسط | پیشرفته

   هر Edge: { source, target, type } — نوع رابطه از RELATION_TYPES با برچسب فارسی.
   جهت یال معنادار است: source —type→ target. */

/* ─────────────────────────── درس‌ها ───────────────────────────
   رنگ اکسنت هر درس با هویت تپش هماهنگ است (همان خانوادهٔ ویکی/بانک تست). */
export const COURSES = [
  { id: 'anatomy', label: 'آناتومی', accent: '#ab8e7c' },
  { id: 'physiology', label: 'فیزیولوژی', accent: '#5b8cc7' },
  { id: 'biochemistry', label: 'بیوشیمی', accent: '#937fcd' },
  { id: 'histology', label: 'بافت‌شناسی', accent: '#77b787' },
  { id: 'pathology', label: 'پاتولوژی', accent: '#e26d6d' },
  { id: 'microbiology', label: 'میکروب‌شناسی', accent: '#8fc79b' },
  { id: 'immunology', label: 'ایمونولوژی', accent: '#a690d8' },
  { id: 'pharmacology', label: 'داروشناسی', accent: '#c2a48c' },
];

/* ─────────────────────────── انواع نود ─────────────────────────── */
export const NODE_TYPES = {
  disease: { label: 'بیماری', glyph: 'disease' },
  concept: { label: 'مفهوم', glyph: 'concept' },
  anatomy: { label: 'ساختار آناتومیک', glyph: 'anatomy' },
  process: { label: 'فرایند فیزیولوژیک', glyph: 'process' },
  pathway: { label: 'مسیر بیوشیمیایی', glyph: 'pathway' },
  drug: { label: 'دارو', glyph: 'drug' },
  cell: { label: 'سلول', glyph: 'cell' },
  molecule: { label: 'مولکول / هورمون', glyph: 'molecule' },
  microorganism: { label: 'میکروارگانیسم', glyph: 'microorganism' },
  finding: { label: 'یافته بالینی', glyph: 'finding' },
  labTest: { label: 'آزمایش', glyph: 'labTest' },
};

/* ─────────────────────────── انواع رابطه ───────────────────────────
   برچسب فارسی هنگام Hover روی یال و در فهرست «ارتباطات مهم» نمایش داده می‌شود. */
export const RELATION_TYPES = {
  part_of: { label: 'بخشی از', short: 'بخشِ' },
  contains: { label: 'شامل', short: 'شامل' },
  located_in: { label: 'واقع در', short: 'در' },
  produces: { label: 'تولید می‌کند', short: 'تولید' },
  regulates: { label: 'تنظیم می‌کند', short: 'تنظیم' },
  activates: { label: 'فعال می‌کند', short: 'فعال‌سازی' },
  inhibits: { label: 'مهار می‌کند', short: 'مهار' },
  causes: { label: 'موجب می‌شود', short: 'علت' },
  leads_to: { label: 'منجر به', short: 'منجر به' },
  associated_with: { label: 'همراه با', short: 'همراه' },
  participates_in: { label: 'شرکت می‌کند در', short: 'مشارکت' },
  targets: { label: 'هدف قرار می‌دهد', short: 'هدف' },
  treated_by: { label: 'درمان با', short: 'درمان' },
  measured_by: { label: 'سنجیده با', short: 'سنجش' },
  related_to: { label: 'مرتبط با', short: 'مرتبط' },
};

export const relationLabel = (type) => RELATION_TYPES[type]?.label ?? 'مرتبط با';
export const courseById = (id) => COURSES.find((course) => course.id === id) ?? null;
export const nodeTypeMeta = (type) => NODE_TYPES[type] ?? { label: type, glyph: 'concept' };

/* ─────────────────────────── نودها ─────────────────────────── */

export const KNOWLEDGE_NODES = [
  /* ── مرکز شبکه: دیابت ─────────────────────────────────────── */
  {
    id: 'diabetes',
    slug: 'diabetes',
    title: 'دیابت',
    englishTitle: 'Diabetes Mellitus',
    type: 'disease',
    courses: ['pathology', 'physiology'],
    description:
      'اختلال متابولیک مزمن با هیپرگلیسمی مزمن، ناشی از نقص ترشح انسولین، عملکرد آن یا هر دو؛ یکی از پرتکرارترین محورهای علوم پایه و بالین.',
    whyImportant:
      'دیابت نمونهٔ کامل یک موضوع بین‌درسی است: فهمش بدون آناتومی پانکراس، فیزیولوژی انسولین، بیوشیمی گلوکز و پاتولوژی عوارض ممکن نیست؛ به همین دلیل مرکز شبکهٔ دانش است.',
    keywords: ['دیابت', 'قند خون', 'diabetes', 'hyperglycemia', 'متابولیسم گلوکز'],
    aliases: ['دیابت شیرین', 'مرض قند', 'Diabetes'],
    prerequisites: ['pancreas', 'insulin', 'glucose-regulation', 'glycolysis', 'insulin-resistance'],
    importance: 5,
    difficulty: 'متوسط',
  },
  {
    id: 't1d',
    slug: 'diabetes-type-1',
    title: 'دیابت نوع ۱',
    englishTitle: 'Type 1 Diabetes',
    type: 'disease',
    courses: ['pathology', 'immunology'],
    description:
      'دیابت وابسته به انسولین با تخریب اتوایمیون سلول‌های بتای جزایر لانگرهانس و کمبود مطلق انسولین؛ شایع در جوانی و مستعد کتواسیدوز.',
    whyImportant: 'الگوی کلاسیک بیماری اتوایمیون اندوکرین و تفکیک آن از نوع ۲، نقطهٔ امتحانی پرتکرار است.',
    keywords: ['دیابت نوع ۱', 'انسولین‌وابسته', 'type 1', 't1d', 'juvenile diabetes'],
    aliases: ['دیابت جوانی', 'IDDM'],
    prerequisites: ['diabetes', 'beta-cell', 'autoimmune-beta-destruction'],
    importance: 5,
    difficulty: 'متوسط',
  },
  {
    id: 't2d',
    slug: 'diabetes-type-2',
    title: 'دیابت نوع ۲',
    englishTitle: 'Type 2 Diabetes',
    type: 'disease',
    courses: ['pathology'],
    description:
      'دیابت مستقل از انسولین با مقاومت به انسولین و نقص نسبی ترشح؛ ۹۰٪ دیابت‌ها، با زمینهٔ چاقی و سندرم متابولیک.',
    whyImportant: 'شایع‌ترین بیماری متابولیک دنیا و هدف اصلی داروهای خوراکی ضددیابت.',
    keywords: ['دیابت نوع ۲', 'مستقل از انسولین', 'type 2', 't2d', 'NIDDM'],
    aliases: ['دیابت بزرگسالی', 'NIDDM'],
    prerequisites: ['diabetes', 'insulin-resistance'],
    importance: 5,
    difficulty: 'متوسط',
  },
  {
    id: 'prediabetes',
    slug: 'prediabetes',
    title: 'پیش‌دیابت',
    englishTitle: 'Prediabetes',
    type: 'disease',
    courses: ['pathology'],
    description:
      'مرحلهٔ مرزی بین نرمال و دیابت؛ گلوکز ناشتا یا تحمل گلوکز مختل و HbA1c بین ۵.۷ تا ۶.۴ درصد — فرصت طلایی پیشگیری.',
    keywords: ['پری‌دیابت', 'pre-diabetes', 'مرحله مرزی'],
    aliases: ['اختلال تحمل گلوکز', 'IGT', 'IFG'],
    prerequisites: ['diabetes', 'hba1c'],
    importance: 3,
    difficulty: 'پایه',
  },
  {
    id: 'insulin-resistance',
    slug: 'insulin-resistance',
    title: 'مقاومت به انسولین',
    englishTitle: 'Insulin Resistance',
    type: 'concept',
    courses: ['physiology', 'pathology'],
    description:
      'کاهش پاسخ بافت‌های هدف به انسولین؛ پانکراس با هایپرانسولینمی جبران می‌کند تا وقتی ظرفیت ترشح فرسوده شود.',
    whyImportant: 'حلقهٔ اتصال چاقی، سندرم متابولیک، کبد چرب و دیابت نوع ۲ — ستون فقرات پاتوفیزیولوژی نوع ۲.',
    keywords: ['مقاومت انسولین', 'insulin resistance', 'هایپرانسولینمی'],
    aliases: ['Insulin Resistance Syndrome'],
    prerequisites: ['insulin', 'insulin-receptor'],
    importance: 5,
    difficulty: 'متوسط',
  },
  {
    id: 'metabolic-syndrome',
    slug: 'metabolic-syndrome',
    title: 'سندرم متابولیک',
    englishTitle: 'Metabolic Syndrome',
    type: 'disease',
    courses: ['pathology'],
    description:
      'خوشهٔ چاقی مرکزی، دیس‌لیپیدمی، هیپرتنشن، هیپرگلیسمی و مقاومت به انسولین؛ خطر قلبی-عروقی را چند برابر می‌کند.',
    keywords: ['سندرم متابولیک', 'metabolic syndrome', 'چاقی مرکزی'],
    aliases: ['سندرم X'],
    prerequisites: ['insulin-resistance'],
    importance: 3,
    difficulty: 'پایه',
  },
  {
    id: 'dka',
    slug: 'diabetic-ketoacidosis',
    title: 'کتواسیدوز دیابتی',
    englishTitle: 'Diabetic Ketoacidosis (DKA)',
    type: 'disease',
    courses: ['pathology', 'physiology'],
    description:
      'عارضهٔ حاد کمبود مطلق انسولین: کتوژنز مهارناشدنی، اسیدوز متابولیک با شکاف آنیونی و کم‌آبی؛ اورژانس تیپ ۱.',
    whyImportant: 'ترکیب کلاسیک بیوشیمی (کتوژنز) و فیزیولوژی (اسید-باز) در یک بیماری؛ مورد محبوب آزمون‌ها.',
    keywords: ['کتواسیدوز', 'dka', 'ketoacidosis', 'شکاف آنیونی'],
    aliases: ['DKA'],
    prerequisites: ['ketogenesis', 't1d', 'insulin'],
    importance: 4,
    difficulty: 'پیشرفته',
  },
  {
    id: 'hypoglycemia',
    slug: 'hypoglycemia',
    title: 'هیپوگلیسمی',
    englishTitle: 'Hypoglycemia',
    type: 'disease',
    courses: ['physiology'],
    description:
      'افت گلوکز خون زیر ۵۵ میلی‌گرم/دسی‌لیتر با تریاد ویتال، علائم نوروگلیکوپنیک و بهبود با خوراکی؛ شایع‌ترین عارضهٔ انسولین‌درمانی.',
    keywords: ['هیپوگلیسمی', 'hypoglycemia', 'افت قند'],
    aliases: ['افت قند خون'],
    prerequisites: ['glucose-regulation', 'insulin'],
    importance: 4,
    difficulty: 'پایه',
  },
  {
    id: 'gestational-diabetes',
    slug: 'gestational-diabetes',
    title: 'دیابت بارداری',
    englishTitle: 'Gestational Diabetes',
    type: 'disease',
    courses: ['pathology', 'physiology'],
    description:
      'هیپرگلیسمی نخستین‌بار در بارداری؛ هورمون‌های جفت مقاومت به انسولین را تشدید می‌کنند و خطر دیابت نوع ۲ آینده را بالا می‌برند.',
    keywords: ['دیابت بارداری', 'gestational', 'بارداری'],
    aliases: ['GDM'],
    prerequisites: ['diabetes', 'insulin-resistance'],
    importance: 3,
    difficulty: 'پایه',
  },

  /* ── عوارض مزمن ───────────────────────────────────────────── */
  {
    id: 'diabetic-neuropathy',
    slug: 'diabetic-neuropathy',
    title: 'نوروپاتی دیابتی',
    englishTitle: 'Diabetic Neuropathy',
    type: 'disease',
    courses: ['pathology'],
    description:
      'آسیب عصبی محیطی و اتونوم به‌دلیل هیپرگلیسمی مزمن و میکروآنژیوپاتی؛ شایع‌ترین شکل، پلی‌نوروپاتی حسگیران متقارن «جوراب و دستکش».',
    keywords: ['نوروپاتی', 'neuropathy', 'اعصاب محیطی'],
    aliases: ['آسیب عصب دیابتی'],
    prerequisites: ['diabetes', 'hyperglycemia'],
    importance: 3,
    difficulty: 'متوسط',
  },
  {
    id: 'diabetic-retinopathy',
    slug: 'diabetic-retinopathy',
    title: 'رتینوپاتی دیابتی',
    englishTitle: 'Diabetic Retinopathy',
    type: 'disease',
    courses: ['pathology'],
    description:
      'میکروآنژیوپاتی شبکیه از میکروآنوریسم و خونریزی تا نئوواسکولاریزاسیون؛ علت نخست کوری در بزرگسالان فعال.',
    keywords: ['رتینوپاتی', 'retinopathy', 'شبکیه'],
    aliases: ['بیماری شبکیه دیابتی'],
    prerequisites: ['diabetes', 'hyperglycemia'],
    importance: 3,
    difficulty: 'متوسط',
  },
  {
    id: 'diabetic-nephropathy',
    slug: 'diabetic-nephropathy',
    title: 'نفروپاتی دیابتی',
    englishTitle: 'Diabetic Nephropathy',
    type: 'disease',
    courses: ['pathology'],
    description:
      'نفروز کلاسیک نودولی (Kimmelstiel-Wilson)، آلبومینوری و افت GFR؛ علت نخست ESRD و هدف درمانی مهارکننده‌های SGLT2/RAAS.',
    keywords: ['نفروپاتی', 'nephropathy', 'آلبومینوری', 'کلیه'],
    aliases: ['بیماری کلیوی دیابتی'],
    prerequisites: ['diabetes', 'hyperglycemia'],
    importance: 3,
    difficulty: 'متوسط',
  },
  {
    id: 'diabetic-foot',
    slug: 'diabetic-foot',
    title: 'پای دیابتی',
    englishTitle: 'Diabetic Foot',
    type: 'finding',
    courses: ['pathology', 'microbiology'],
    description:
      'زخم مزمن پا از تقاطع نوروپاتی (بی‌حسی و تغییر شکل)، ایسکمی و عفونت؛ شایع‌ترین علت آمپوتاسیون غیرتروماتیک.',
    keywords: ['پای دیابتی', 'diabetic foot', 'زخم پا'],
    aliases: ['زخم پای دیابتی'],
    prerequisites: ['diabetic-neuropathy', 'atherosclerosis', 'diabetic-infections'],
    importance: 3,
    difficulty: 'پایه',
  },
  {
    id: 'atherosclerosis',
    slug: 'atherosclerosis',
    title: 'آترواسکلروز',
    englishTitle: 'Atherosclerosis',
    type: 'disease',
    courses: ['pathology'],
    description:
      'تشکیل پلاک لیپیدی-التهابی در شریان‌ها؛ دیابت مسیر آن را با گلیکاسیون، دیس‌لیپیدمی و اختلال اندوتلیوم شتاب می‌دهد.',
    keywords: ['آترواسکلروز', 'atherosclerosis', 'پلاک', 'قلب و عروق'],
    aliases: ['تصلب شرایین'],
    prerequisites: ['diabetes'],
    importance: 3,
    difficulty: 'متوسط',
  },

  /* ── آناتومی و سلول ───────────────────────────────────────── */
  {
    id: 'pancreas',
    slug: 'pancreas',
    title: 'پانکراس',
    englishTitle: 'Pancreas',
    type: 'anatomy',
    courses: ['anatomy'],
    description:
      'غدهٔ دوکارهٔ صفاقی خلفی: بخش اگزوکرین آنزیم گوارشی و بخش اندوکرین (جزایر لانگرهانس) هورمون‌های متابولیک ترشح می‌کند.',
    keywords: ['پانکراس', 'pancreas', 'لوزالمعده'],
    aliases: ['لوزالمعده'],
    prerequisites: [],
    importance: 4,
    difficulty: 'پایه',
  },
  {
    id: 'islets',
    slug: 'islets-of-langerhans',
    title: 'جزایر لانگرهانس',
    englishTitle: 'Islets of Langerhans',
    type: 'anatomy',
    courses: ['anatomy', 'histology'],
    description:
      'جزیره‌های اندوکرین پراکنده در پانکراس؛ سلول‌های بتا (مرکز، ~۷۰٪)، آلفا، دلتا و PP را در چیدمان منظم نگه می‌دارد.',
    whyImportant: 'پل بافت‌شناسی و فیزیولوژی: هر هورمون متابولیک از همین جزیره‌ها بیرون می‌آید.',
    keywords: ['جزایر لانگرهانس', 'islets', 'langerhans', 'پانکراس اندوکرین'],
    aliases: ['پانکراس اندوکرین'],
    prerequisites: ['pancreas'],
    importance: 4,
    difficulty: 'پایه',
  },
  {
    id: 'liver',
    slug: 'liver',
    title: 'کبد',
    englishTitle: 'Liver',
    type: 'anatomy',
    courses: ['anatomy'],
    description:
      'کارخانهٔ متابولیک بدن: محل گلیکوژن‌سازی، گلوکونئوژنز، کتوژنز و لیپوژنز؛ پاسخ‌دهندهٔ اصلی به انسولین و گلوکاگون.',
    keywords: ['کبد', 'liver', 'جگر'],
    aliases: ['جگر'],
    prerequisites: [],
    importance: 3,
    difficulty: 'پایه',
  },
  {
    id: 'skeletal-muscle',
    slug: 'skeletal-muscle',
    title: 'عضلهٔ اسکلتی',
    englishTitle: 'Skeletal Muscle',
    type: 'anatomy',
    courses: ['anatomy'],
    description:
      'بزرگ‌ترین بافت مصرف‌کنندهٔ گلوکز پس‌از غذا؛ برداشت گلوکز وابسته به انسولین آن از طریق GLUT4 انجام می‌شود.',
    keywords: ['عضله اسکلتی', 'skeletal muscle', 'ماهیچه'],
    aliases: ['ماهیچهٔ اسکلتی'],
    prerequisites: [],
    importance: 3,
    difficulty: 'پایه',
  },
  {
    id: 'adipose-tissue',
    slug: 'adipose-tissue',
    title: 'بافت چربی',
    englishTitle: 'Adipose Tissue',
    type: 'anatomy',
    courses: ['anatomy', 'histology'],
    description:
      'اندام اندوکرین فعال: آدیپوکاین‌های چاقی (لپتین، TNF-α، رزیستین) مقاومت به انسولین را تغذیه می‌کنند.',
    keywords: ['بافت چربی', 'adipose', 'چاقی', 'آدیپوکاین'],
    aliases: ['نسج چربی'],
    prerequisites: [],
    importance: 2,
    difficulty: 'پایه',
  },
  {
    id: 'beta-cell',
    slug: 'beta-cell',
    title: 'سلول بتا',
    englishTitle: 'Beta Cell',
    type: 'cell',
    courses: ['histology'],
    description:
      'سلول غالب جزایر، ترشح‌کنندهٔ انسولین و پپتید C؛ حساس‌ترین سنجش‌گر گلوکز خون با گیرندهٔ GLUT2/گلوکوکیناز.',
    keywords: ['سلول بتا', 'beta cell', 'β-cell'],
    aliases: ['بتا سلول'],
    prerequisites: ['islets'],
    importance: 4,
    difficulty: 'پایه',
  },
  {
    id: 'alpha-cell',
    slug: 'alpha-cell',
    title: 'سلول آلفا',
    englishTitle: 'Alpha Cell',
    type: 'cell',
    courses: ['histology'],
    description: 'سلول پری‌فرری جزیره، ترشح‌کنندهٔ گلوکاگون؛ واکنش اول بدن به هیپوگلیسمی.',
    keywords: ['سلول آلفا', 'alpha cell'],
    aliases: ['آلفا سلول'],
    prerequisites: ['islets'],
    importance: 3,
    difficulty: 'پایه',
  },
  {
    id: 'delta-cell',
    slug: 'delta-cell',
    title: 'سلول دلتا',
    englishTitle: 'Delta Cell',
    type: 'cell',
    courses: ['histology'],
    description: 'ترشح‌کنندهٔ سوماتوستاتین؛ تنظیم‌گر بازدارندهٔ هم‌زمان انسولین و گلوکاگون.',
    keywords: ['سلول دلتا', 'delta cell', 'سوماتوستاتین'],
    aliases: ['دلتا سلول'],
    prerequisites: ['islets'],
    importance: 2,
    difficulty: 'پایه',
  },

  /* ── مولکول‌ها و هورمون‌ها ─────────────────────────────────── */
  {
    id: 'insulin',
    slug: 'insulin',
    title: 'انسولین',
    englishTitle: 'Insulin',
    type: 'molecule',
    courses: ['physiology', 'biochemistry'],
    description:
      'هورمون انبارش انرژی: گلوکز و اسید آمینه را به داخل سلول می‌برد، گلیکوژن/چربی/پروتئین‌سازی را روشن و تجزیه را خاموش می‌کند.',
    whyImportant: 'پرکاربردترین هورمون در آموزش پزشکی: هر درسی — از بیوشیمی تا فارما — از آن شروع می‌شود.',
    keywords: ['انسولین', 'insulin', 'هورمون لوزالمعده'],
    aliases: ['Insulin'],
    prerequisites: ['beta-cell'],
    importance: 5,
    difficulty: 'پایه',
  },
  {
    id: 'glucagon',
    slug: 'glucagon',
    title: 'گلوکاگون',
    englishTitle: 'Glucagon',
    type: 'molecule',
    courses: ['physiology'],
    description:
      'هورمون رفع‌فقر سوختی: در کبد گلیکوژنولیز و گلوکونئوژنز را روشن و در بافت چربی لیپولیز را فعال می‌کند.',
    keywords: ['گلوکاگون', 'glucagon'],
    aliases: [],
    prerequisites: ['alpha-cell'],
    importance: 4,
    difficulty: 'پایه',
  },
  {
    id: 'glucose',
    slug: 'blood-glucose',
    title: 'گلوکز خون',
    englishTitle: 'Blood Glucose',
    type: 'molecule',
    courses: ['biochemistry', 'physiology'],
    description:
      'سوخت ترجیحی مغز و محور تنظیم هورمونی؛ بازهٔ طبیعی ناشتا ۷۰ تا ۱۰۰ و بعد از غذا زیر ۱۴۰ میلی‌گرم/دسی‌لیتر.',
    keywords: ['گلوکز', 'glucose', 'قند خون'],
    aliases: ['دکستروز'],
    prerequisites: [],
    importance: 5,
    difficulty: 'پایه',
  },
  {
    id: 'insulin-receptor',
    slug: 'insulin-receptor',
    title: 'گیرندهٔ انسولین',
    englishTitle: 'Insulin Receptor',
    type: 'molecule',
    courses: ['biochemistry'],
    description:
      'تیروزین‌کیناز چهارزنجیره‌ای (α₂β₂)؛ اتوفسفوریلاسیون و فعال‌سازی آبشار IRS/PI3K/Akt — نمونهٔ درسی گیرنده‌های کینازی.',
    keywords: ['گیرنده انسولین', 'insulin receptor', 'تیروزین کیناز'],
    aliases: ['INSR', 'RTK'],
    prerequisites: ['insulin'],
    importance: 4,
    difficulty: 'متوسط',
  },
  {
    id: 'glut4',
    slug: 'glut4',
    title: 'ناقل GLUT4',
    englishTitle: 'GLUT4 Transporter',
    type: 'molecule',
    courses: ['biochemistry'],
    description:
      'ناقل گلوکز حساس به انسولین در حباب‌های درون‌سلولی؛ با Akt به غشا منتقل و Vmax برداشت گلوکز را چند برابر می‌کند.',
    keywords: ['glut4', 'ناقل گلوکز', 'glucose transporter'],
    aliases: ['GLUT-4', 'SLC2A4'],
    prerequisites: ['insulin-receptor'],
    importance: 4,
    difficulty: 'متوسط',
  },
  {
    id: 'glp1',
    slug: 'glp-1',
    title: 'هورمون GLP-1',
    englishTitle: 'GLP-1 (Incretin)',
    type: 'molecule',
    courses: ['physiology'],
    description:
      'اینکرتین روده‌ای: ترشح وابسته به گلوکزِ انسولین را تقویت، گلوکاگون را مهار و تخلیهٔ معده را کند می‌کند.',
    keywords: ['glp-1', 'اینکرتین', 'incretin', 'گلوکاگون‌مانند'],
    aliases: ['پپتید شبه گلوکاگون'],
    prerequisites: ['insulin-secretion'],
    importance: 3,
    difficulty: 'متوسط',
  },
  {
    id: 'c-peptide',
    slug: 'c-peptide',
    title: 'پپتید C',
    englishTitle: 'C-Peptide',
    type: 'molecule',
    courses: ['physiology'],
    description:
      'زنجیرهٔ اتصالی پروانسولین که هم‌ارز انسولین ترشح می‌شود؛ نشانگر درون‌زای عملکرد سلول بتا و تفکیک هیپوگلیسمی درون‌زا از تزریقی.',
    keywords: ['c-peptide', 'پپتید c', 'پروانسولین'],
    aliases: ['Connecting Peptide'],
    prerequisites: ['insulin'],
    importance: 2,
    difficulty: 'پیشرفته',
  },
  {
    id: 'gad-antibodies',
    slug: 'gad-antibodies',
    title: 'آنتی‌بادی‌های ضد GAD',
    englishTitle: 'Anti-GAD Antibodies',
    type: 'molecule',
    courses: ['immunology'],
    description:
      'پرشایع‌ترین نشانگر اتوایمیون در دیابت نوع ۱؛ همراه IA-2، ZnT8 و آنتی‌بادی سلول جزیره، سال‌ها پیش از بروز بیماری مثبت می‌شود.',
    keywords: ['gad', 'آنتی‌بادی', 'autoantibody', 'اتوایمیون'],
    aliases: ['Anti-GAD65', 'IA-2'],
    prerequisites: ['autoimmune-beta-destruction'],
    importance: 3,
    difficulty: 'متوسط',
  },

  /* ── فرایندهای فیزیولوژیک ─────────────────────────────────── */
  {
    id: 'glucose-regulation',
    slug: 'glucose-homeostasis',
    title: 'تنظیم قند خون',
    englishTitle: 'Glucose Homeostasis',
    type: 'process',
    courses: ['physiology'],
    description:
      'تعادل دوسویهٔ انسولین (ذخیره) و گلوکاگون (مصرف) بر سر گلوکز خون؛ نمونهٔ آموزشی بازخورد منفی در بدن.',
    keywords: ['تنظیم قند', 'homeostasis', 'همئوستاز گلوکز'],
    aliases: ['همئوستاز گلوکز'],
    prerequisites: ['insulin', 'glucagon'],
    importance: 5,
    difficulty: 'پایه',
  },
  {
    id: 'insulin-secretion',
    slug: 'insulin-secretion',
    title: 'ترشح انسولین',
    englishTitle: 'Insulin Secretion',
    type: 'process',
    courses: ['physiology'],
    description:
      'گلوکز از GLUT2 وارد و با گلوکوکیناز فسفوریله می‌شود؛ ATP/ADP بالاتر، بستن کانال K-ATP، دپولاریزاسیون، ورود کلسیم و اگزوسیتوز.',
    whyImportant: 'نمونهٔ درسی اتصال متابولیسم به الکتریسیتهٔ سلولی — و هدف مستقیم سولفونیل‌اوره‌ها.',
    keywords: ['ترشح انسولین', 'insulin secretion', 'کانال k-atp', 'گلوکوکیناز'],
    aliases: [],
    prerequisites: ['beta-cell', 'glucose'],
    importance: 4,
    difficulty: 'متوسط',
  },
  {
    id: 'glucose-uptake',
    slug: 'glucose-uptake',
    title: 'برداشت گلوکز',
    englishTitle: 'Cellular Glucose Uptake',
    type: 'process',
    courses: ['physiology', 'biochemistry'],
    description:
      'ورود گلوکز به عضله و بافت چربی از GLUT4 وابسته به انسولین؛ گلوکز پس از فسفوریلاسیون با هگزوکیناز از سلول خارج نمی‌شود.',
    keywords: ['برداشت گلوکز', 'glucose uptake', 'انتقال گلوکز'],
    aliases: [],
    prerequisites: ['glut4', 'insulin-signaling'],
    importance: 4,
    difficulty: 'متوسط',
  },
  {
    id: 'autoimmune-beta-destruction',
    slug: 'autoimmune-beta-cell-destruction',
    title: 'تخریب اتوایمیون سلول بتا',
    englishTitle: 'Autoimmune Beta-Cell Destruction',
    type: 'process',
    courses: ['immunology'],
    description:
      'نفوذ لنفوسیت‌های T سیتیتوتوکسیک و التهاب جزیره‌ای (Insulitis)؛ کمبود انسولین وقتی ظاهر می‌شود که ~۸۰٪ جرم سلولی از بین رفته باشد.',
    keywords: ['اتوایمیون', 'autoimmune', 'insulitis', 'تخریب سلول بتا'],
    aliases: ['التهاب جزایر', 'Insulitis'],
    prerequisites: ['beta-cell', 'insulin'],
    importance: 4,
    difficulty: 'متوسط',
  },

  /* ── مسیرهای بیوشیمیایی ───────────────────────────────────── */
  {
    id: 'insulin-signaling',
    slug: 'insulin-signaling',
    title: 'پیام‌رسانی انسولین',
    englishTitle: 'Insulin Signaling Pathway',
    type: 'pathway',
    courses: ['biochemistry'],
    description:
      'آبشار IRS → PI3K → PIP3 → Akt؛ Akt انتقال GLUT4، سنتز گلیکوژن (مهار GSK-3) و لیپوژنز را هماهنگ می‌کند.',
    keywords: ['insulin signaling', 'pi3k', 'akt', 'irs'],
    aliases: ['آبشار PI3K-Akt'],
    prerequisites: ['insulin-receptor'],
    importance: 4,
    difficulty: 'پیشرفته',
  },
  {
    id: 'glycolysis',
    slug: 'glycolysis',
    title: 'گلیکولیز',
    englishTitle: 'Glycolysis',
    type: 'pathway',
    courses: ['biochemistry'],
    description:
      'تجزیهٔ گلوکز به دو پیرووات در سیتوپلاسم با خالص ۲ ATP و ۲ NADH؛ آنزیم نرخ‌ساز فسفوفروکتوکیناز-۱ (PFK-1).',
    keywords: ['گلیکولیز', 'glycolysis', 'pfk-1', 'پیرووات'],
    aliases: ['مسیر امبدن-مایرهوف'],
    prerequisites: ['glucose'],
    importance: 5,
    difficulty: 'متوسط',
  },
  {
    id: 'gluconeogenesis',
    slug: 'gluconeogenesis',
    title: 'گلوکونئوژنز',
    englishTitle: 'Gluconeogenesis',
    type: 'pathway',
    courses: ['biochemistry'],
    description:
      'ساخت گلوکز تازه از لاکتات، گلیسرول و اسیدهای آمینه گلوکوژنیک در کبد؛ چهار آنزیم کلیدی دور زدن گام‌های برگشت‌ناپذیر گلیکولیز.',
    keywords: ['گلوکونئوژنز', 'gluconeogenesis', 'پیرووات کربوکسیلاز'],
    aliases: ['نوسازی گلوکز'],
    prerequisites: ['glycolysis'],
    importance: 4,
    difficulty: 'پیشرفته',
  },
  {
    id: 'glycogenesis',
    slug: 'glycogenesis',
    title: 'گلیکوژنز',
    englishTitle: 'Glycogenesis',
    type: 'pathway',
    courses: ['biochemistry'],
    description:
      'سنتز گلیکوژن در کبد و عضله با گلیکوژن‌سینتاز؛ انسولین آن را فعال و GSK-3 را مهار می‌کند — انبارش گلوکز مازاد.',
    keywords: ['گلیکوژنز', 'glycogenesis', 'گلیکوژن', 'گلیکوژن سینتاز'],
    aliases: ['سنتز گلیکوژن'],
    prerequisites: ['glycolysis'],
    importance: 3,
    difficulty: 'متوسط',
  },
  {
    id: 'glycogenolysis',
    slug: 'glycogenolysis',
    title: 'گلیکوژنولیز',
    englishTitle: 'Glycogenolysis',
    type: 'pathway',
    courses: ['biochemistry'],
    description:
      'تجزیهٔ گلیکوژن به گلوکز-۱-فسفات با گلیکوژن‌فسفوریلاز؛ در کبد برای خون، در عضله فقط برای خودش — تفاوت کلیدی آزمونی.',
    keywords: ['گلیکوژنولیز', 'glycogenolysis', 'فسفوریلاز'],
    aliases: ['تجزیه گلیکوژن'],
    prerequisites: ['glycogenesis'],
    importance: 3,
    difficulty: 'متوسط',
  },
  {
    id: 'tca-cycle',
    slug: 'tca-cycle',
    title: 'چرخهٔ کربس',
    englishTitle: 'TCA / Krebs Cycle',
    type: 'pathway',
    courses: ['biochemistry'],
    description:
      'هستهٔ هوازی متابولیسم در میتوکندری: استیل-CoA به CO₂، NADH و FADH₂ برای زنجیرهٔ انتقال الکترون؛ تقاطع همهٔ مسیرها.',
    keywords: ['کربس', 'tca', 'krebs', 'چرخه اسید سیتریک'],
    aliases: ['چرخه اسید سیتریک', 'چرخه کربس'],
    prerequisites: ['glycolysis'],
    importance: 4,
    difficulty: 'متوسط',
  },
  {
    id: 'beta-oxidation',
    slug: 'beta-oxidation',
    title: 'بتا-اکسیداسیون',
    englishTitle: 'Fatty Acid Beta-Oxidation',
    type: 'pathway',
    courses: ['biochemistry'],
    description:
      'برش پیوستهٔ دوکربنی اسیدهای چرب به استیل-CoA در میتوکندری؛ منبع سوبسترا کتوژنز در روزه‌داری و DKA.',
    keywords: ['بتا اکسیداسیون', 'beta oxidation', 'اسید چرب'],
    aliases: ['اکسیداسیون اسید چرب'],
    prerequisites: ['tca-cycle'],
    importance: 3,
    difficulty: 'متوسط',
  },
  {
    id: 'ketogenesis',
    slug: 'ketogenesis',
    title: 'کتوژنز',
    englishTitle: 'Ketogenesis',
    type: 'pathway',
    courses: ['biochemistry'],
    description:
      'ساخت استواستات، بتاهیدروکسی‌بوتیرات و استون از استیل-CoA در کبد؛ سوخت مغز در قحطی — و آتش DKA بی‌انسولین.',
    keywords: ['کتوژنز', 'ketogenesis', 'کتون', 'استیل coa'],
    aliases: ['ساخت اجسام کتونی'],
    prerequisites: ['beta-oxidation'],
    importance: 4,
    difficulty: 'پیشرفته',
  },

  /* ── داروشناسی ────────────────────────────────────────────── */
  {
    id: 'insulin-therapy',
    slug: 'insulin-therapy',
    title: 'انسولین درمانی',
    englishTitle: 'Insulin Therapy',
    type: 'drug',
    courses: ['pharmacology'],
    description:
      'تنها درمان تیپ ۱ و پایهٔ درمان پیشرفتهٔ تیپ ۲؛ خانواده‌های سریع، کوتاه، میان‌اثر و طول‌اثر با فارماکوکینتیک متفاوت.',
    keywords: ['انسولین درمانی', 'insulin therapy', 'انسولین باسولار'],
    aliases: ['انسولین تزریقی'],
    prerequisites: ['insulin', 't1d'],
    importance: 5,
    difficulty: 'متوسط',
  },
  {
    id: 'metformin',
    slug: 'metformin',
    title: 'متفورمین',
    englishTitle: 'Metformin',
    type: 'drug',
    courses: ['pharmacology'],
    description:
      'خط اول دیابت نوع ۲: فعال‌سازی AMPK و مهار گلوکونئوژنز کبدی؛ وزن‌خنثی، بدون هیپوگلیسمی تک‌دارویی، احتیاط در نارسایی کلیه.',
    keywords: ['متفورمین', 'metformin', 'گلوکوفاژ'],
    aliases: ['گلوکوفاژ'],
    prerequisites: ['gluconeogenesis', 't2d'],
    importance: 5,
    difficulty: 'پایه',
  },
  {
    id: 'sulfonylureas',
    slug: 'sulfonylureas',
    title: 'سولفونیل‌اوره‌ها',
    englishTitle: 'Sulfonylureas',
    type: 'drug',
    courses: ['pharmacology'],
    description:
      'بستن کانال K-ATP سلول بتا و ترشح وابسته به کلسیم انسولین؛ اثرمند فقط با بافت بتای زنده — خطر هیپوگلیسمی و افزایش وزن.',
    keywords: ['سولفونیل اوره', 'sulfonylurea', 'گلیبورید'],
    aliases: ['گلیبورید', 'گلی‌بنکلامید'],
    prerequisites: ['insulin-secretion', 't2d'],
    importance: 3,
    difficulty: 'پایه',
  },
  {
    id: 'glp1-agonists',
    slug: 'glp1-agonists',
    title: 'آگونیست‌های GLP-1',
    englishTitle: 'GLP-1 Receptor Agonists',
    type: 'drug',
    courses: ['pharmacology'],
    description:
      'تقلید اینکرتین با مقاومت به دی‌پپتیدیل‌پپتیداز-۴؛ ترشح وابسته به گلوکز، سیری و کاهش وزن — لیراگلوتید و سمگلوتید.',
    keywords: ['glp-1', 'سمگلوتید', 'لیراگلوتید', 'اگزناتید'],
    aliases: ['لیراگلوتید', 'سمگلوتید'],
    prerequisites: ['glp1', 't2d'],
    importance: 3,
    difficulty: 'متوسط',
  },
  {
    id: 'sglt2-inhibitors',
    slug: 'sglt2-inhibitors',
    title: 'مهارکننده‌های SGLT2',
    englishTitle: 'SGLT2 Inhibitors',
    type: 'drug',
    courses: ['pharmacology'],
    description:
      'دفع گلوکز از ادرار با مهار ناقل SGLT2 نفرون؛ حفاظت قلبی-کلیوی مستقل از کاهش قند — اداگلیفلوزین و امپاگلیفلوزین.',
    keywords: ['sglt2', 'اداگلیفلوزین', 'امپاگلیفلوزین', 'گلوکوزوری دارویی'],
    aliases: ['گلیفلوزین‌ها', 'Flozins'],
    prerequisites: ['t2d', 'diabetic-nephropathy'],
    importance: 3,
    difficulty: 'متوسط',
  },

  /* ── ایمنی‌شناسی و میکروب ─────────────────────────────────── */
  {
    id: 'diabetic-infections',
    slug: 'diabetes-related-infections',
    title: 'عفونت‌های مرتبط با دیابت',
    englishTitle: 'Diabetes-Related Infections',
    type: 'concept',
    courses: ['microbiology'],
    description:
      'هیپرگلیسمی عملکرد نوتروفیل و ایمنی سلولی را کور می‌کند: عفونت‌های مکرر ادراری، کاندیدیازیس و عفونت‌های عمیق بافت نرم.',
    keywords: ['عفونت', 'infection', 'نوتروفیل', 'ایمنی'],
    aliases: ['استعداد عفونی دیابت'],
    prerequisites: ['hyperglycemia'],
    importance: 2,
    difficulty: 'پایه',
  },
  {
    id: 'mucormycosis',
    slug: 'mucormycosis',
    title: 'موکورمیکوز',
    englishTitle: 'Mucormycosis',
    type: 'microorganism',
    courses: ['microbiology'],
    description:
      'قارچ فلاسفوم با میل آهنی؛ رینوسربال، تهاجمی و کشنده در زمینهٔ کتواسیدوز — اورژانس تشخیصی انکوژنولوژیکِ دیابت.',
    keywords: ['موکور', 'mucormycosis', 'زیگومایکوز', 'فلاسفوم'],
    aliases: ['زیگومایکوز'],
    prerequisites: ['dka'],
    importance: 2,
    difficulty: 'پیشرفته',
  },

  /* ── یافته‌ها و آزمایش‌ها ──────────────────────────────────── */
  {
    id: 'hyperglycemia',
    slug: 'hyperglycemia',
    title: 'هیپرگلیسمی',
    englishTitle: 'Hyperglycemia',
    type: 'finding',
    courses: ['pathology', 'physiology'],
    description:
      'گلوکز بالاتر از آستانهٔ کلیوی (~۱۸۰) با گلوکوزوری اسموتیک؛ حاد: پلی‌اوری و پرنوشی، مزمن: گلیکاسیون پروتئین و عوارض ریزعروقی.',
    keywords: ['هیپرگلیسمی', 'hyperglycemia', 'قند بالا'],
    aliases: ['قند خون بالا'],
    prerequisites: ['glucose-regulation'],
    importance: 4,
    difficulty: 'پایه',
  },
  {
    id: 'polyuria',
    slug: 'polyuria',
    title: 'پرادراری (پلی‌اوری)',
    englishTitle: 'Polyuria',
    type: 'finding',
    courses: ['physiology'],
    description:
      'ادرار حجم بالا از کشیدگی اسموتیک گلوکز ادراری؛ اولین حلقهٔ مثلث کلاسیک پلی‌اوری، پلی‌دیپسی، کاهش وزن.',
    keywords: ['پلی اوری', 'polyuria', 'ادرار زیاد'],
    aliases: ['پلی‌اوری'],
    prerequisites: ['hyperglycemia'],
    importance: 3,
    difficulty: 'پایه',
  },
  {
    id: 'polydipsia',
    slug: 'polydipsia',
    title: 'پرنوشی (پلی‌دیپسی)',
    englishTitle: 'Polydipsia',
    type: 'finding',
    courses: ['physiology'],
    description: 'تشنگی شدید جبرانی کم‌آبی پلی‌اوری؛ همراه همیشگی پرادراری در شروع دیابت.',
    keywords: ['پلی دیپسی', 'polydipsia', 'تشنگی'],
    aliases: ['پلی‌دیپسی'],
    prerequisites: ['polyuria'],
    importance: 2,
    difficulty: 'پایه',
  },
  {
    id: 'fasting-glucose',
    slug: 'fasting-plasma-glucose',
    title: 'قند خون ناشتا (FPG)',
    englishTitle: 'Fasting Plasma Glucose',
    type: 'labTest',
    courses: ['physiology'],
    description:
      'گلوکز پس از ۸ ساعت ناشتا: نرمال زیر ۱۰۰، پیش‌دیابت ۱۰۰-۱۲۵، دیابت ۱۲۶ به بالا (در دو نوبت) میلی‌گرم/دسی‌لیتر.',
    keywords: ['fpg', 'قند ناشتا', 'fasting glucose'],
    aliases: ['FPG'],
    prerequisites: ['glucose'],
    importance: 4,
    difficulty: 'پایه',
  },
  {
    id: 'hba1c',
    slug: 'hba1c',
    title: 'هموگلوبین A1c',
    englishTitle: 'Hemoglobin A1c',
    type: 'labTest',
    courses: ['pathology', 'physiology'],
    description:
      'حافظهٔ ۳ ماههٔ قند خون: گلیکاسیون غیرآنزیمی هموگلوبین بتا؛ دیابت از ۶.۵ درصد — معیار کنترل و هدف درمان.',
    whyImportant: 'پل بین بیوشیمی (گلیکاسیون) و بالین (پایش درمان) — پرتکرارترین آزمایش این حوزه.',
    keywords: ['hba1c', 'a1c', 'هموگلوبین گلیکوزیله'],
    aliases: ['هموگلوبین گلیکوزیله'],
    prerequisites: ['glucose'],
    importance: 5,
    difficulty: 'پایه',
  },
  {
    id: 'ogtt',
    slug: 'ogtt',
    title: 'تست تحمل گلوکز (OGTT)',
    englishTitle: 'Oral Glucose Tolerance Test',
    type: 'labTest',
    courses: ['physiology'],
    description:
      '۷۵ گرم گلوکز خوراکی و سنجش ۲ ساعت بعد: زیر ۱۴۰ نرمال، ۱۴۰-۱۹۹ مختل، ۲۰۰ به بالا دیابت؛ استاندارد بارداری.',
    keywords: ['ogtt', 'تحمل گلوکز', 'تست تحمل'],
    aliases: ['کرایه‌ای گلوکز'],
    prerequisites: ['fasting-glucose'],
    importance: 3,
    difficulty: 'پایه',
  },
  {
    id: 'ketones',
    slug: 'blood-ketones',
    title: 'کتون‌های خون',
    englishTitle: 'Blood Ketones',
    type: 'labTest',
    courses: ['pathology'],
    description:
      'سنجش بتاهیدروکسی‌بوتیرات؛ ستون تشخیص و پیگیری کتواسیدوز، همراه با گاز خون و شکاف آنیونی.',
    keywords: ['کتون', 'ketones', 'بتا هیدروکسی بوتیرات'],
    aliases: ['اجسام کتونی'],
    prerequisites: ['ketogenesis'],
    importance: 3,
    difficulty: 'متوسط',
  },
];

/* ─────────────────────────── یال‌ها ───────────────────────────
   source —type→ target. هر رابطه یک حقیقت علمی است، نه یک خط تزئینی. */
export const KNOWLEDGE_EDGES = [
  /* رده‌بندی دیابت */
  { source: 't1d', target: 'diabetes', type: 'part_of' },
  { source: 't2d', target: 'diabetes', type: 'part_of' },
  { source: 'gestational-diabetes', target: 'diabetes', type: 'part_of' },
  { source: 'prediabetes', target: 't2d', type: 'leads_to' },
  { source: 'prediabetes', target: 'diabetes', type: 'related_to' },

  /* زنجیرهٔ آناتومی → سلول → هورمون */
  { source: 'islets', target: 'pancreas', type: 'part_of' },
  { source: 'beta-cell', target: 'islets', type: 'part_of' },
  { source: 'alpha-cell', target: 'islets', type: 'part_of' },
  { source: 'delta-cell', target: 'islets', type: 'part_of' },
  { source: 'beta-cell', target: 'insulin', type: 'produces' },
  { source: 'beta-cell', target: 'c-peptide', type: 'produces' },
  { source: 'alpha-cell', target: 'glucagon', type: 'produces' },
  { source: 'delta-cell', target: 'insulin-secretion', type: 'inhibits' },
  { source: 'islets', target: 'insulin-secretion', type: 'located_in' },

  /* فیزیولوژی تنظیم قند */
  { source: 'insulin', target: 'glucose-regulation', type: 'regulates' },
  { source: 'glucagon', target: 'glucose-regulation', type: 'regulates' },
  { source: 'glucose', target: 'insulin-secretion', type: 'activates' },
  { source: 'glp1', target: 'insulin-secretion', type: 'activates' },
  { source: 'insulin-secretion', target: 'insulin', type: 'produces' },
  { source: 'insulin', target: 'insulin-receptor', type: 'activates' },
  { source: 'insulin-receptor', target: 'insulin-signaling', type: 'activates' },
  { source: 'insulin-signaling', target: 'glucose-uptake', type: 'activates' },
  { source: 'glut4', target: 'glucose-uptake', type: 'participates_in' },
  { source: 'glucose-uptake', target: 'skeletal-muscle', type: 'located_in' },
  { source: 'glucose-uptake', target: 'adipose-tissue', type: 'located_in' },
  { source: 'insulin', target: 'glucose', type: 'regulates' },
  { source: 'glucagon', target: 'glucose', type: 'regulates' },

  /* مقاومت و سندرم متابولیک */
  { source: 'insulin-resistance', target: 't2d', type: 'causes' },
  { source: 'insulin-resistance', target: 'metabolic-syndrome', type: 'part_of' },
  { source: 'adipose-tissue', target: 'insulin-resistance', type: 'causes' },
  { source: 'gestational-diabetes', target: 't2d', type: 'leads_to' },

  /* اتوایمیون تیپ ۱ */
  { source: 'autoimmune-beta-destruction', target: 'beta-cell', type: 'targets' },
  { source: 'autoimmune-beta-destruction', target: 't1d', type: 'causes' },
  { source: 't1d', target: 'gad-antibodies', type: 'measured_by' },

  /* بیوشیمی: هستهٔ متابولیسم */
  { source: 'glucose', target: 'glycolysis', type: 'participates_in' },
  { source: 'glycolysis', target: 'tca-cycle', type: 'leads_to' },
  { source: 'beta-oxidation', target: 'tca-cycle', type: 'participates_in' },
  { source: 'beta-oxidation', target: 'ketogenesis', type: 'participates_in' },
  { source: 'glycogenesis', target: 'liver', type: 'located_in' },
  { source: 'glycogenolysis', target: 'liver', type: 'located_in' },
  { source: 'gluconeogenesis', target: 'liver', type: 'located_in' },
  { source: 'ketogenesis', target: 'liver', type: 'located_in' },
  { source: 'glycogenesis', target: 'skeletal-muscle', type: 'located_in' },
  { source: 'insulin', target: 'glycogenesis', type: 'activates' },
  { source: 'insulin', target: 'glycolysis', type: 'activates' },
  { source: 'insulin', target: 'gluconeogenesis', type: 'inhibits' },
  { source: 'insulin', target: 'glycogenolysis', type: 'inhibits' },
  { source: 'insulin', target: 'ketogenesis', type: 'inhibits' },
  { source: 'glucagon', target: 'glycogenolysis', type: 'activates' },
  { source: 'glucagon', target: 'gluconeogenesis', type: 'activates' },
  { source: 'glucagon', target: 'ketogenesis', type: 'activates' },
  { source: 'gluconeogenesis', target: 'glucose', type: 'produces' },
  { source: 'glycogenolysis', target: 'glucose', type: 'produces' },

  /* هیپرگلیسمی و تابلوی بالینی */
  { source: 'diabetes', target: 'hyperglycemia', type: 'causes' },
  { source: 'hyperglycemia', target: 'polyuria', type: 'causes' },
  { source: 'polyuria', target: 'polydipsia', type: 'causes' },
  { source: 'hyperglycemia', target: 'diabetic-neuropathy', type: 'causes' },
  { source: 'hyperglycemia', target: 'diabetic-retinopathy', type: 'causes' },
  { source: 'hyperglycemia', target: 'diabetic-nephropathy', type: 'causes' },
  { source: 'hyperglycemia', target: 'atherosclerosis', type: 'causes' },
  { source: 'hyperglycemia', target: 'diabetic-infections', type: 'causes' },
  { source: 'diabetes', target: 'hba1c', type: 'measured_by' },
  { source: 'diabetes', target: 'fasting-glucose', type: 'measured_by' },
  { source: 'diabetes', target: 'ogtt', type: 'measured_by' },
  { source: 'prediabetes', target: 'hba1c', type: 'measured_by' },
  { source: 'prediabetes', target: 'fasting-glucose', type: 'measured_by' },

  /* کتواسیدوز */
  { source: 't1d', target: 'dka', type: 'associated_with' },
  { source: 'ketogenesis', target: 'ketones', type: 'measured_by' },
  { source: 'dka', target: 'ketones', type: 'measured_by' },
  { source: 'dka', target: 'mucormycosis', type: 'associated_with' },
  { source: 'hypoglycemia', target: 'glucagon', type: 'treated_by' },

  /* پای دیابتی: تقاطع سه مسیر */
  { source: 'diabetic-neuropathy', target: 'diabetic-foot', type: 'causes' },
  { source: 'atherosclerosis', target: 'diabetic-foot', type: 'causes' },
  { source: 'diabetic-infections', target: 'diabetic-foot', type: 'causes' },

  /* داروشناسی */
  { source: 't1d', target: 'insulin-therapy', type: 'treated_by' },
  { source: 't2d', target: 'metformin', type: 'treated_by' },
  { source: 't2d', target: 'sulfonylureas', type: 'treated_by' },
  { source: 't2d', target: 'glp1-agonists', type: 'treated_by' },
  { source: 't2d', target: 'sglt2-inhibitors', type: 'treated_by' },
  { source: 't2d', target: 'insulin-therapy', type: 'treated_by' },
  { source: 'metformin', target: 'gluconeogenesis', type: 'inhibits' },
  { source: 'sulfonylureas', target: 'insulin-secretion', type: 'activates' },
  { source: 'glp1-agonists', target: 'glp1', type: 'related_to' },
  { source: 'glp1-agonists', target: 'insulin-secretion', type: 'activates' },
  { source: 'diabetic-nephropathy', target: 'sglt2-inhibitors', type: 'treated_by' },
  { source: 'insulin-therapy', target: 'hypoglycemia', type: 'causes' },
  { source: 'insulin-therapy', target: 'insulin', type: 'related_to' },
  { source: 'metformin', target: 'insulin-resistance', type: 'treated_by' },
];

/* زنجیرهٔ نمونهٔ پرامپت: پانکراس → … → گلیکولیز
   برای Path View پیش‌فرض و نمایش زنجیرهٔ کلاسیک. */
export const SHOWCASE_CHAIN = [
  'pancreas',
  'islets',
  'beta-cell',
  'insulin',
  'insulin-receptor',
  'glut4',
  'glucose-uptake',
  'glycolysis',
];

/* نودهای شروع پیشنهادی صفحه اصلی — پرترافیک‌ترین مفاهیم */
export const STARTING_POINTS = ['diabetes', 'insulin', 'glucose-regulation', 'glycolysis'];
