/*
 * دادهٔ Mock پلتفرم «آزمون‌های هماهنگ تپش».
 *
 * اصل طراحی:
 *  - Exam و Question دو Entity مستقل‌اند؛ Exam فقط با questionIds به سؤال‌ها reference می‌دهد.
 *  - زمان‌های آزمون‌ها نسبت به «الان» ساخته می‌شوند تا همهٔ وضعیت‌ها (ثبت‌نام فعال،
 *    در حال برگزاری، پایان‌یافته با کارنامه) همیشه در دمو زنده باشند. در نسخهٔ Backend
 *    این فیلدها از سرور می‌آیند و ثابت‌اند.
 *  - سؤال‌ها نمونهٔ تالیفی تیم تپش‌اند؛ کلید پاسخ هرگز به UI محیط آزمون داده نمی‌شود
 *    (فقط بعد از submit از طریق fetchReviewQuestions برمی‌گردد).
 */

const DAY = 86400000;
const MINUTE = 60000;
const now = () => Date.now();

/* زمان نزدیک به رأس ساعت بعدی — برای دمو Countdown با حس واقعی */
function atCleanHour(offsetDays, hour, minute = 0) {
  const date = new Date(Date.now() + offsetDays * DAY);
  date.setHours(hour, minute, 0, 0);
  if (offsetDays === 0 && date.getTime() < Date.now()) date.setDate(date.getDate() + 1);
  return date.getTime();
}

/* ────────────────────────── آزمون‌ها (EXAM) ────────────────────────── */

export const EXAMS = [
  {
    id: 'exam-basic-national-01',
    slug: 'basic-sciences-national-01',
    title: 'آزمون جامع هماهنگ علوم پایه تپش',
    shortName: 'جامع علوم پایه',
    type: 'national',
    organizer: 'تیم آزمون تپش',
    description:
      'جامع‌ترین آزمون هماهنگ علوم پایه بین دانشجویان سراسر کشور؛ با سؤال‌های تالیفی هم‌سو با آزمون علوم پایه وزارت بهداشت طراحی شده تا نقطهٔ ایستایی خود را قبل از آزمون اصلی بسنجید.',
    subject: 'علوم پایه پزشکی',
    topics: ['فیزیولوژی', 'بیوشیمی', 'آناتومی', 'بافت‌شناسی', 'جنین‌شناسی', 'ایمونولوژی'],
    /* بودجه‌بندی آزمون — بخش‌های هر درس که در آزمون می‌آید (count: سهم تعدادی برای Backend) */
    budget: [
      { topic: 'فیزیولوژی', count: 22, sections: ['فیزیولوژی سلولی و خون', 'سیستم عصبی', 'سیستم قلبی-عروقی', 'سیستم تنفسی', 'سیستم کلیوی', 'غدد و گوارش'] },
      { topic: 'بیوشیمی', count: 20, sections: ['ساختار پروتئین‌ها', 'آنزیم‌ها', 'گلیکولیز و چرخهٔ کربس', 'متابولیسم لیپیدها', 'ویتامین‌ها و هورمون‌ها'] },
      { topic: 'آناتومی', count: 18, sections: ['استخوان‌شناسی', 'مفاصل و عضلات', 'سینه و شکم', 'سر و گردن', 'عرق‌ونسا'] },
      { topic: 'بافت‌شناسی', count: 16, sections: ['بافت پوششی', 'بافت همبند', 'بافت عضلانی و عصبی', 'سیستم گردش خون', 'غدد درون‌ریز'] },
      { topic: 'جنین‌شناسی', count: 12, sections: ['لقاح و لانه‌گزینی', 'جنین‌شناسی عمومی', 'جنین‌شناسی قلب', 'جنین‌شناسی عصبی', 'ناهنجاری‌های مادرزادی'] },
      { topic: 'ایمونولوژی', count: 12, sections: ['سلول‌های ایمنی', 'آنتی‌ژن و آنتی‌بادی', 'کمپلمان', 'ایمنی سلولی و هومورال', 'آلرژی و خودایمنی'] },
    ],
    difficulty: 'hard',
    audience: 'دانشجویان پزشکی، دندان‌پزشکی و داروسازی',
    level: 'پایان دورهٔ علوم پایه',
    duration: 120,
    questionCount: 100,
    startTime: atCleanHour(2, 10, 0),
    endTime: atCleanHour(2, 10, 0) + 120 * MINUTE,
    registrationOpenAt: now() - 3 * DAY,
    registrationDeadline: atCleanHour(2, 10, 0) - 12 * 60 * MINUTE,
    resultReleaseAt: atCleanHour(2, 10, 0) + 120 * MINUTE + 6 * 60 * MINUTE,
    participantsCount: 3482,
    universities: ['تهران', 'شهید بهشتی', 'ایران', 'مشهد', 'تبریز', 'شیراز', 'اصفهان', 'سایر دانشگاه‌ها'],
    accent: '#61D192',
    glyph: 'shield',
    featured: true,
    rules: {
      negativeMarking: -0.25,
      allowBackNavigation: true,
      allowAnswerChange: true,
      attemptLimit: 1,
      deadlineMode: 'exam_end',
      allowMarking: true,
    },
  },
  {
    id: 'exam-physio-live-01',
    slug: 'physio-heart-live-01',
    title: 'آزمون هماهنگ فیزیولوژی قلب',
    shortName: 'هماهنگ فیزیولوژی',
    type: 'subject',
    organizer: 'تیم آزمون تپش',
    description:
      'آزمون هماهنگ موضوعی روی فیزیولوژی قلب و گردش خون؛ هم‌زمان با دانشجویان سراسر کشور و با کارنامه و رتبهٔ لحظه‌ای بعد از پایان.',
    subject: 'فیزیولوژی',
    topics: ['فیزیولوژی قلب', 'پتانسیل عمل قلبی', 'چرخهٔ قلبی', 'ECG', 'تنظیم فشار خون'],
    budget: [
      { topic: 'فیزیولوژی قلب', count: 8, sections: ['پتانسیل عمل قلبی', 'چرخهٔ قلبی', 'ECG', 'تنظیم فشار خون'] },
    ],
    difficulty: 'medium',
    audience: 'دانشجویان علوم پزشکی — ترم ۳ به بالا',
    level: 'میان‌ترم',
    duration: 90,
    questionCount: 8,
    startTime: now() - 32 * MINUTE,
    endTime: now() + 88 * MINUTE,
    registrationOpenAt: now() - 2 * DAY,
    registrationDeadline: now() - 32 * MINUTE,
    resultReleaseAt: now() + 88 * MINUTE + 45 * MINUTE,
    participantsCount: 1286,
    accent: '#937fcd',
    glyph: 'orbit',
    rules: {
      negativeMarking: -0.25,
      allowBackNavigation: true,
      allowAnswerChange: true,
      attemptLimit: 1,
      deadlineMode: 'exam_end',
      allowMarking: true,
    },
  },
  {
    id: 'exam-daily-quiz',
    slug: 'daily-quiz',
    title: 'آزمونک روزانه تپش',
    shortName: 'آزمونک روزانه',
    type: 'quiz',
    organizer: 'تیم محتوای تپش',
    description:
      'پنج سؤال کوتاه هر روز از مباحث پرتکرار؛ بدون ثبت‌نام، همیشه در دسترس — برای گرم‌کردن ذهن قبل از مطالعه.',
    subject: 'علوم پایه',
    topics: ['هیبرید دائم', 'چرخهٔ کربس', 'ویتامین‌ها', 'فیزیولوژی عمومی'],
    budget: [
      { topic: 'علوم پایه', count: 5, sections: ['هیبرید دائم', 'چرخهٔ کربس', 'ویتامین‌ها', 'فیزیولوژی عمومی'] },
    ],
    difficulty: 'easy',
    audience: 'همهٔ دانشجویان علوم پزشکی',
    level: 'متفرقه',
    duration: 5,
    questionCount: 5,
    alwaysAvailable: true,
    startTime: now() - DAY,
    endTime: now() + DAY,
    resultReleaseAt: 0,
    participantsCount: 5217,
    accent: '#e0b45c',
    glyph: 'spark',
    rules: {
      negativeMarking: 0,
      allowBackNavigation: true,
      allowAnswerChange: true,
      attemptLimit: 3,
      deadlineMode: 'per_attempt',
      allowMarking: false,
    },
  },
  {
    id: 'exam-biochem-past-01',
    slug: 'biochem-subject-01',
    title: 'آزمون موضوعی بیوشیمی — متابولیسم',
    shortName: 'موضوعی بیوشیمی',
    type: 'subject',
    organizer: 'تیم آزمون تپش',
    description:
      'آزمون موضوعی بیوشیمی با تمرکز روی گلیکولیز، چرخهٔ کربس و متابولیسم انرژی؛ برگزارشده در مرداد ماه.',
    subject: 'بیوشیمی',
    topics: ['گلیکولیز', 'چرخهٔ کربس', 'متساوی‌انرژی', 'ساختار پروتئین'],
    budget: [
      { topic: 'بیوشیمی', count: 6, sections: ['گلیکولیز', 'چرخهٔ کربس', 'متساوی‌انرژی', 'ساختار پروتئین'] },
    ],
    difficulty: 'medium',
    audience: 'دانشجویان پزشکی و دندان‌پزشکی',
    level: 'پایان مبحث',
    duration: 45,
    questionCount: 6,
    startTime: now() - 12 * DAY,
    endTime: now() - 12 * DAY + 45 * MINUTE,
    registrationOpenAt: now() - 18 * DAY,
    registrationDeadline: now() - 12 * DAY,
    resultReleaseAt: now() - 12 * DAY + 3 * 60 * MINUTE,
    participantsCount: 842,
    accent: '#77b787',
    glyph: 'delta',
    rules: {
      negativeMarking: -0.25,
      allowBackNavigation: true,
      allowAnswerChange: true,
      attemptLimit: 1,
      deadlineMode: 'exam_end',
      allowMarking: true,
    },
  },
  {
    id: 'exam-basic-mock-aug',
    slug: 'basic-sciences-mock-aug',
    title: 'آزمون آزمایشی علوم پایه مرداد',
    shortName: 'آزمایشی مرداد',
    type: 'mock',
    organizer: 'تیم آزمون تپش',
    description:
      'شبیه‌ساز کامل آزمون علوم پایه وزارت بهداشت با تراز و رتبهٔ کشوری؛ برای سنجش وضعیت قبل از جمع‌بندی.',
    subject: 'علوم پایه پزشکی',
    topics: ['فیزیولوژی', 'بیوشیمی', 'آناتومی'],
    budget: [
      { topic: 'فیزیولوژی', count: 50, sections: ['سیستم قلبی-عروقی', 'سیستم تنفسی', 'سیستم کلیوی', 'سیستم عصبی مرکزی'] },
      { topic: 'بیوشیمی', count: 40, sections: ['گلیکولیز', 'چرخهٔ کربس', 'متابولیسم لیپیدها', 'ویتامین‌ها'] },
      { topic: 'آناتومی', count: 30, sections: ['استخوان‌شناسی', 'سینه و شکم', 'سر و گردن'] },
    ],
    difficulty: 'hard',
    audience: 'دانشجویان علوم پزشکی',
    level: 'شبیه‌ساز رسمی',
    duration: 150,
    questionCount: 120,
    startTime: now() - 26 * DAY,
    endTime: now() - 26 * DAY + 150 * MINUTE,
    registrationOpenAt: now() - 33 * DAY,
    registrationDeadline: now() - 26 * DAY,
    resultReleaseAt: now() - 26 * DAY + 180 * MINUTE,
    participantsCount: 2614,
    accent: '#5b8cc7',
    glyph: 'arch',
    rules: {
      negativeMarking: -0.25,
      allowBackNavigation: true,
      allowAnswerChange: true,
      attemptLimit: 1,
      deadlineMode: 'exam_end',
      allowMarking: true,
    },
  },
  {
    id: 'exam-first-term-01',
    slug: 'first-term-comprehensive-01',
    title: 'آزمون جامع اول ترم — آبان',
    shortName: 'جامع اول ترم',
    type: 'comprehensive',
    organizer: 'تیم آزمون تپش',
    description:
      'آزمون جامع شروع نیم‌سال؛ پوشش مباحث ترم جاری برای جهت‌گیری مطالعه از ابتدای سال تحصیلی. ثبت‌نام به‌زودی باز می‌شود.',
    subject: 'علوم پایه',
    topics: ['فیزیولوژی', 'آناتومی', 'هیستولوژی'],
    budget: [
      { topic: 'فیزیولوژی', count: 25, sections: ['فیزیولوژی سلولی', 'سیستم عصبی', 'قلب و عروق'] },
      { topic: 'آناتومی', count: 20, sections: ['استخوان‌شناسی', 'عضله‌شناسی'] },
      { topic: 'هیستولوژی', count: 15, sections: ['بافت پوششی', 'بافت همبند'] },
    ],
    difficulty: 'medium',
    audience: 'دانشجویان جدیدالورود و ترم ۲',
    level: 'شروع ترم',
    duration: 90,
    questionCount: 60,
    startTime: atCleanHour(48, 16, 0),
    endTime: atCleanHour(48, 16, 0) + 90 * MINUTE,
    registrationOpenAt: atCleanHour(10, 12, 0),
    registrationDeadline: atCleanHour(48, 16, 0) - 12 * 60 * MINUTE,
    resultReleaseAt: atCleanHour(48, 16, 0) + 90 * MINUTE + 6 * 60 * MINUTE,
    participantsCount: 0,
    accent: '#937fcd',
    glyph: 'compass',
    rules: {
      negativeMarking: -0.25,
      allowBackNavigation: true,
      allowAnswerChange: true,
      attemptLimit: 1,
      deadlineMode: 'exam_end',
      allowMarking: true,
    },
  },
];

/* ────────────────────────── بانک سؤال (QUESTION — Entity مستقل) ────────────────────────── */

export const QUESTIONS = [
  /* ── آزمون هماهنگ فیزیولوژی قلب (LIVE) ── */
  {
    id: 'q-phys-01',
    examId: 'exam-physio-live-01',
    subject: 'فیزیولوژی',
    topic: 'پتانسیل عمل قلبی',
    difficulty: 'medium',
    stem: 'فاز صفر پتانسیل عمل سلول‌های گرهی (Pacemaker) گره سینوسی‌دهلیزی عمدتاً ناشی از ورود کدام یون است؟',
    options: [
      'ورود سریع سدیم از کانال‌های Fast Sodium',
      'ورود کلسیم از کانال‌های نوع L',
      'خروج پتاسیم از کانال‌های تأخیری',
      'ورود کلر از کانال‌های لیگاندی',
    ],
    correctAnswer: 1,
    explanation:
      'برخلاف سلول‌های عضلانی قلب که فاز صفرشان وابسته به جریان سریع سدیم است، در سلول‌های گرهی فاز صفر از ورود کلسیم از کانال‌های نوع L (جریان کلسیمی آهسته) ایجاد می‌شود؛ به همین دلیل سرعت صعود پتانسیل عمل در آن‌ها کمتر است.',
    keyPoint: 'فاز صفر سلول گرهی = جریان کلسیمی آهسته (L-type)؛ فاز صفر میوکارد = جریان سریع سدیم.',
    related: { lesson: 'پتانسیل عمل قلبی', wiki: 'Cardiac Action Potential' },
  },
  {
    id: 'q-phys-02',
    examId: 'exam-physio-live-01',
    subject: 'فیزیولوژی',
    topic: 'ECG',
    difficulty: 'medium',
    stem: 'فاصلهٔ PR در نوار ECG نرمال، نمایانگر کدام رویداد است؟',
    options: [
      'زمان هدایت از گره دهلیزی-بطنی تا شروع انقباض بطن',
      'مدت انقباض کامل بطن‌ها',
      'زمان دپولاریزاسیون دهلیزها',
      'فاصلهٔ بین بسته‌شدن دریچهٔ میترال و آئورت',
    ],
    correctAnswer: 0,
    explanation:
      'فاصلهٔ PR از شروع موج P تا شروع کمپلکس QRS است و نشان‌دهندهٔ زمان هدایت ایمپالس از دهلیزها، عبور از گره AV و سیستم هیس-پورکینژه تا شروع دپولاریزاسیون بطن‌هاست (نرمال ۰٫۱۲ تا ۰٫۲ ثانیه).',
    keyPoint: 'PR = تأخیر هدایتی گره AV؛ طولانی‌شدن آن یعنی بلوک AV درجهٔ اول.',
    related: { lesson: 'الکتروکاردیوگرافی پایه', wiki: 'PR interval' },
  },
  {
    id: 'q-phys-03',
    examId: 'exam-physio-live-01',
    subject: 'فیزیولوژی',
    topic: 'چرخهٔ قلبی',
    difficulty: 'easy',
    stem: 'صدای اول قلب (S1) در کدام رخداد ایجاد می‌شود؟',
    options: [
      'بسته‌شدن دریچه‌های میترال و تریکوسپید',
      'باز‌شدن دریچه‌های آئورت و پولمونار',
      'بسته‌شدن دریچه‌های آئورت و پولمونار',
      'پر شدن سریع بطن‌ها در دیاستول',
    ],
    correctAnswer: 0,
    explanation:
      'S1 در ابتدای سیستول و هم‌زمان با بسته‌شدن دریچه‌های دهلیزی-بطنی (میترال و تریکوسپید) تولید می‌شود و آغاز انقباض بطن را اعلام می‌کند.',
    keyPoint: 'S1 = بسته‌شدن AV valve در شروع سیستول؛ S2 = بسته‌شدن سمی‌لونار در پایان سیستول.',
    related: { lesson: 'چرخهٔ قلبی و صداهای قلب', wiki: 'Heart sounds' },
  },
  {
    id: 'q-phys-04',
    examId: 'exam-physio-live-01',
    subject: 'فیزیولوژی',
    topic: 'منحنی فرانک-استارلینگ',
    difficulty: 'hard',
    stem: 'بر اساس مکانیزم فرانک-استارلینگ، افزایش بازگشت وریدی مستقیماً با کدام تغییر همراه است؟',
    options: [
      'کاهش طول فیبر عضلهٔ قلبی در پایان دیاستول',
      'افزایش طول فیبر و افزایش نیروی انقباضی در سیستول بعدی',
      'کاهش برون‌ده قلبی بدون تغییر در حجم ضربه‌ای',
      'افزایش مقاومت محیطی عروق',
    ],
    correctAnswer: 1,
    explanation:
      'افزایش پیش‌بار (بازگشت وریدی) طول فیبر میوکارد در پایان دیاستول را زیاد می‌کند؛ کشیده‌تر شدن سارکومر تا حد بهینه، حساسیت تروپونین به کلسیم و در نتیجه نیروی انقباضی و حجم ضربه‌ای را افزایش می‌دهد.',
    keyPoint: 'پیش‌بار بیشتر → سارکومر کشیده‌تر → انقباض قوی‌تر؛ بدون نیاز به تغییر اینوتروپیک.',
    related: { lesson: 'تنظیم برون‌ده قلبی', wiki: 'Frank–Starling law' },
  },
  {
    id: 'q-phys-05',
    examId: 'exam-physio-live-01',
    subject: 'فیزیولوژی',
    topic: 'تنظیم عصبی قلب',
    difficulty: 'medium',
    stem: 'اثر استیل‌کولین پاراسمپاتیک روی گره سینوسی‌دهلیزی با کدام مکانیزم موجب کاهش ضربان قلب می‌شود؟',
    options: [
      'افزایش جریان ورودی کلسیم به سلول گرهی',
      'افزایش هدایت پتاسیمی و کندی فاز ۴ دپولاریزاسیون',
      'افزایش حساسیت میوکارد به نوراپی‌نفرین',
      'تسریع هدایت گره AV',
    ],
    correctAnswer: 1,
    explanation:
      'استیل‌کولین از طریق گیرنده‌های موسکارینی M2، کانال‌های پتاسیمی اصلاح‌شدهٔ ACh را باز می‌کند؛ خروج پتاسیم، غشا را هایپرپلاریزه کرده و شیب فاز ۴ (پتانسیل گرهی) را کم می‌کند و ضربان کاهش می‌یابد.',
    keyPoint: 'پاراسمپات = کندی فاز ۴ با بازشدن کانال K (IK-ACh) و کاهش cAMP.',
    related: { lesson: 'کنترل عصبی قلب', wiki: 'Vagal tone' },
  },
  {
    id: 'q-phys-06',
    examId: 'exam-physio-live-01',
    subject: 'فیزیولوژی',
    topic: 'همودینامیک',
    difficulty: 'medium',
    stem: 'در تنگی دریچهٔ آئورت، کدام تغییر در فشار بطن چپ و آئورت انتظار می‌رود؟',
    options: [
      'افزایش گرادیان فشار سیستولی بین بطن چپ و آئورت',
      'کاهش فشار سیستولی بطن چپ',
      'افزایش فشار دیاستولی آئورت نسبت به حالت نرمال با الگوی یکسان',
      'برابری کامل فشار بطن و آئورت در طول سیستول',
    ],
    correctAnswer: 0,
    explanation:
      'در تنگی آئورت، خروج خون با مانع مواجه می‌شود؛ فشار سیستولی بطن چپ برای غلبه بر تنگی بالا می‌رود در حالی که فشار آئورت پایین‌تر است و گرادیان فشار سیستولی مشخصی ایجاد می‌شود.',
    keyPoint: 'هر تنگی دریچه‌ای = گرادیان فشار در محل تنگی؛ شدت تنگی با اندازهٔ همین گرادیان سنجیده می‌شود.',
    related: { lesson: 'بیماری‌های دریچه‌ای', wiki: 'Aortic stenosis' },
  },
  {
    id: 'q-phys-07',
    examId: 'exam-physio-live-01',
    subject: 'فیزیولوژی',
    topic: 'پتانسیل عمل قلبی',
    difficulty: 'medium',
    stem: 'دورهٔ تحریک‌ناپذیری مؤثر میوکارد بطنی تقریباً هم‌زمان با کدام فاز پتانسیل عمل است؟',
    options: [
      'فاز صفر',
      'بیشتر فازهای ۲ و ۳ (پلاتو و دپولاریزاسیون نهایی)',
      'فاز ۴',
      'فاز ۱',
    ],
    correctAnswer: 1,
    explanation:
      'به دلیل باز‌ماندن کانال‌های کلسیمی در طول پلاتو (فاز ۲) و بازشدن تدریجی کانال‌های پتاسیمی در فاز ۳، میوکارد بطنی تا اواخر فاز ۳ قادر به ایجاد پتانسیل عمل جدید نیست؛ این ویژگی از تترانی قلب جلوگیری می‌کند.',
    keyPoint: 'ARP طولانی میوکارد = جلوگیری از تترانی قلب؛ برخلاف عضلهٔ اسکلتی.',
    related: { lesson: 'خواص الکتریکی میوکارد', wiki: 'Cardiac refractory period' },
  },
  {
    id: 'q-phys-08',
    examId: 'exam-physio-live-01',
    subject: 'فیزیولوژی',
    topic: 'تنظیم فشار خون',
    difficulty: 'hard',
    stem: 'در واکنش فوری به افت ناگهانی فشار خون، کدام تغییر ابتدا رخ می‌دهد؟',
    options: [
      'کاهش ترشح آلدوسترون از غدد آدرنال',
      'افزایش فعالیت سمپاتیک و انقباض وریدها و شریانچه‌ها',
      'افزایش دفع آب و سدیم از کلیه',
      'کاهش ضربان قلب از راه عصب واگ',
    ],
    correctAnswer: 1,
    explanation:
      'رفلکس بارورسپتوری با کاهش فشار فعال می‌شود: کاهش فایرینگ بارورسپتورها مرکز عروقی را به افزایش فعال‌سازی سمپاتیک وامیدارد؛ انقباض وریدها (افزایش بازگشت وریدی) و شریانچه‌ها همراه با افزایش ضربان، فشار را سریع جبران می‌کند.',
    keyPoint: 'جبران فوری فشار = رفلکس بارورسپتوری و سمپاتیک؛ مکانیزم‌های هورمونی (RAAS) دیرتر وارد عمل می‌شوند.',
    related: { lesson: 'تنظیم فشار خون', wiki: 'Baroreflex' },
  },

  /* ── آزمونک روزانه (Quiz) ── */
  {
    id: 'q-daily-01',
    examId: 'exam-daily-quiz',
    subject: 'اندوکرینولوژی',
    topic: 'هیپوفیز',
    difficulty: 'easy',
    stem: 'کدام هورمون از هیپوفیز خلفی ترشح می‌شود؟',
    options: ['پرولاکتین', 'هورمون رشد', 'اکسی‌توسین', 'تیروئید محرک (TSH)'],
    correctAnswer: 2,
    explanation:
      'هیپوفیز خلفی فقط اکسی‌توسین و وازوپرسین (ADH) را که در هیپوتالاموس ساخته شده‌اند ذخیره و آزاد می‌کند؛ بقیهٔ هورمون‌های فهرست از هیپوفیز قدامی ترشح می‌شوند.',
    keyPoint: 'هیپوفیز خلفی = ADH + اکسی‌توسین؛ ساخت در هیپوتالاموس، ذخیره در پایهٔ عصبی.',
    related: { lesson: 'هیپوفیز و هورمون‌های آن', wiki: 'Posterior pituitary' },
  },
  {
    id: 'q-daily-02',
    examId: 'exam-daily-quiz',
    subject: 'فیزیولوژی',
    topic: 'سیستم رنین-آنژیوتانسین',
    difficulty: 'easy',
    stem: 'آنزیم مبدل آنژیوتانسین (ACE) در کدام اندام محل عمل اصلی خود را دارد؟',
    options: ['کبد', 'کلیه', 'ریه', 'قلب'],
    correctAnswer: 2,
    explanation:
      'ACE عمدتاً توسط اندوتلیوم مویرگ‌های ریوی آنژیوتانسین ۱ را به آنژیوتانسین ۲ تبدیل می‌کند؛ به همین دلیل مسیر ریه نقطهٔ کلیدی فعال‌سازی این سیستم است.',
    keyPoint: 'رنین از کلیه، ACE از ریه؛ آنژیوتانسینوژن از کبد.',
    related: { lesson: 'سیستم رنین-آنژیوتانسین-آلدوسترون', wiki: 'Renin–angiotensin system' },
  },
  {
    id: 'q-daily-03',
    examId: 'exam-daily-quiz',
    subject: 'بیوشیمی',
    topic: 'ویتامین‌ها',
    difficulty: 'easy',
    stem: 'کدام ویتامین محلول در چربی است و کمبود آن با اختلال انعقاد خون همراه است؟',
    options: ['ویتامین C', 'ویتامین K', 'ویتامین B12', 'ویتامین B6'],
    correctAnswer: 1,
    explanation:
      'ویتامین K محلول در چربی است و به‌عنوان کوفاکتور گاما-کربوکسیلاسیون عوامل انعقادی II، VII، IX و X عمل می‌کند؛ کمبود آن زمان پروترومبین را افزایش می‌دهد.',
    keyPoint: 'ویتامین K → کربوکسیلاسیون فاکتورهای ۲،۷،۹،۱۰؛ حافظه: «1972».',
    related: { lesson: 'ویتامین‌های محلول در چربی', wiki: 'Vitamin K' },
  },
  {
    id: 'q-daily-04',
    examId: 'exam-daily-quiz',
    subject: 'فیزیولوژی',
    topic: 'تعادل اسید-باز',
    difficulty: 'easy',
    stem: 'محدودهٔ طبیعی pH خون شریانی کدام است؟',
    options: ['۶٫۸ تا ۷٫۲', '۷٫۳۵ تا ۷٫۴۵', '۷٫۵۵ تا ۷٫۶۵', '۷٫۰ تا ۷٫۱۰'],
    correctAnswer: 1,
    explanation:
      'pH طبیعی خون شریانی بین ۷٫۳۵ تا ۷٫۴۵ نگه داشته می‌شود؛ بافر بی‌کربنات، تنفس و کلیه سه ستون اصلی این تنظیم‌اند.',
    keyPoint: 'pH شریانی نرمال = ۷٫۳۵–۷٫۴۵؛ زیر ۷٫۳۵ اسیدوز، بالای ۷٫۴۵ آلکالوز.',
    related: { lesson: 'تعادل اسید و باز', wiki: 'Acid–base homeostasis' },
  },
  {
    id: 'q-daily-05',
    examId: 'exam-daily-quiz',
    subject: 'آناتومی',
    topic: 'سیستم اسکلتی',
    difficulty: 'easy',
    stem: 'بلندترین و قوی‌ترین استخوان بدن انسان کدام است؟',
    options: ['استخوان تیبیا', 'استخوان فمور', 'استخوان هیومروس', 'استخوان فیبولا'],
    correctAnswer: 1,
    explanation:
      'استخوان فمور (ران) بلندترین، قوی‌ترین و سنگین‌ترین استخوان بدن است و بار وزنی تنه را به اندام تحتانی منتقل می‌کند.',
    keyPoint: 'فمور = بلندترین استخوان؛ استاپی‌س (گیرهٔ رکابی گوش) کوچک‌ترین.',
    related: { lesson: 'استخوان‌های اندام تحتانی', wiki: 'Femur' },
  },

  /* ── آزمون موضوعی بیوشیمی (گذشته — با Attempt نمونه برای کاربر) ── */
  {
    id: 'q-bio-01',
    examId: 'exam-biochem-past-01',
    subject: 'بیوشیمی',
    topic: 'گلیکولیز',
    difficulty: 'medium',
    stem: 'آنزیم نام‌گذاری‌کننده و تعیین‌کنندهٔ سرعت (Rate-limiting) مسیر گلیکولیز کدام است؟',
    options: ['هگزوکیناز', 'فسفوفروکتوکیناز-۱ (PFK-1)', 'پیرووات کیناز', 'آلدولاز'],
    correctAnswer: 1,
    explanation:
      'PFK-1 حساس‌ترین و مهم‌ترین نقطهٔ کنترل گلیکولیز است؛ با ATP آلوستریک مهار و با AMP و فروکتوز ۲و۶ بی‌فسفات فعال می‌شود و سرعت کل مسیر را تعیین می‌کند.',
    keyPoint: 'PFK-1 = شیر اصلی گلیکولیز؛ F2,6BP فعال‌کنندهٔ قوی‌ترین آن.',
    related: { lesson: 'گلیکولیز و تنظیم آن', wiki: 'Phosphofructokinase 1' },
  },
  {
    id: 'q-bio-02',
    examId: 'exam-biochem-past-01',
    subject: 'بیوشیمی',
    topic: 'چرخهٔ کربس',
    difficulty: 'medium',
    stem: 'چرخهٔ اسید سیتریک عمدتاً در کدام بخش سلول رخ می‌دهد؟',
    options: ['سیتوپلاسم', 'ماتریکس میتوکندری', 'غشای داخلی میتوکندری', 'شبکهٔ اندوپلاسمی زبر'],
    correctAnswer: 1,
    explanation:
      'آنزیم‌های چرخهٔ کربس در ماتریکس میتوکندری قرار دارند؛ فقط سوکسینات دهیدروژناز در غشای داخلی مستقر است و مستقیماً به زنجیرهٔ انتقال الکترون وصل می‌شود.',
    keyPoint: 'چرخهٔ کربس = ماتریکس میتوکندری؛ زنجیرهٔ ETC = غشای داخلی.',
    related: { lesson: 'چرخهٔ کربس', wiki: 'Citric acid cycle' },
  },
  {
    id: 'q-bio-03',
    examId: 'exam-biochem-past-01',
    subject: 'بیوشیمی',
    topic: 'ساختار پروتئین',
    difficulty: 'medium',
    stem: 'پیوندهای دی‌سولفیدی بین باقی‌مانده‌های سیستئین به کدام سطح ساختاری پروتئین تعلق دارند؟',
    options: ['ساختار اول', 'ساختار دوم', 'ساختار سوم', 'ساختار چهارم'],
    correctAnswer: 2,
    explanation:
      'پیوند دی‌سولفید از اکسیداسیون گروه‌های سولفیدریل دو سیستئین به‌وجود می‌آید و پایداری تاشدگی سه‌بعدی (ساختار سوم) را تأمین می‌کند؛ در ساختار اول فقط توالی اسیدهای آمینه ثبت می‌شود.',
    keyPoint: 'دی‌سولفید = پل پایدارکنندهٔ ساختار سوم؛ الگوی تاخوردگی را قفل می‌کند.',
    related: { lesson: 'سطوح ساختاری پروتئین', wiki: 'Disulfide bond' },
  },
  {
    id: 'q-bio-04',
    examId: 'exam-biochem-past-01',
    subject: 'بیوشیمی',
    topic: 'متساوی‌انرژی',
    difficulty: 'hard',
    stem: 'بازدهٔ انرژی خالص ATP از متابولیسم کامل یک مولکول گلوکز در حضور اکسیژن حدوداً چند است؟',
    options: ['۲ مولکول ATP', '۱۸ مولکول ATP', '۳۰ تا ۳۲ مولکول ATP', '۶۸ مولکول ATP'],
    correctAnswer: 2,
    explanation:
      'با احتساب گلیکولیز، چرخهٔ کربس و فسفوریلاسیون اکسیداتیو و با فرض شاتل‌های مختلف (مالات-آسپارتات یا گلیسرول فسفات) بازده خالص حدود ۳۰ تا ۳۲ ATP است.',
    keyPoint: 'گلوکز هوازی ≈ ۳۰–۳۲ ATP؛ بی‌هوازی فقط ۲ ATP.',
    related: { lesson: 'فسفوریلاسیون اکسیداتیو', wiki: 'Cellular respiration' },
  },
  {
    id: 'q-bio-05',
    examId: 'exam-biochem-past-01',
    subject: 'بیوشیمی',
    topic: 'متابولیسم اسید آمینه',
    difficulty: 'medium',
    stem: 'دهندهٔ اصلی گروه متیل در واکنش‌های متیلااسیون بدن کدام مولکول است؟',
    options: ['اس-آدنوزیل متیونین (SAM)', 'کولین', 'تیامین پیروفسفات', 'استیل کوآ'],
    correctAnswer: 0,
    explanation:
      'SAM از واکنش متیونین با ATP ساخته می‌شود و فعال‌ترین دهندهٔ گروه متیل در سنتز نوروترانسمیترها، DNA و فسفولیپیدهاست؛ پس از دهش متیل به اس-آدنوزیل هموسیستئین تبدیل می‌شود.',
    keyPoint: 'SAM = دهندهٔ جهانی گروه متیل؛ چرخهٔ متیونین-هموسیستئین را به‌خاطر بسپار.',
    related: { lesson: 'متابولیسم متیونین', wiki: 'S-Adenosyl methionine' },
  },
  {
    id: 'q-bio-06',
    examId: 'exam-biochem-past-01',
    subject: 'بیوشیمی',
    topic: 'انرژی عضله',
    difficulty: 'easy',
    stem: 'ذخیرهٔ فسفاژنی عضله که در چند ثانیهٔ اول فعالیت شدید انرژی تولید می‌کند، کدام است؟',
    options: ['ATP ذخیره‌شده در میتوکندری', 'کراتین فسفات', 'گلیکوژن عضله', 'اسید لاکتیک'],
    correctAnswer: 1,
    explanation:
      'کراتین فسفات با انتقال فسفات خود به ADP توسط کراتین کیناز، سریع‌ترین منبع بازساخت ATP در شروع فعالیت انفجاری عضله است؛ ظرفیت آن فقط چند ثانیه است.',
    keyPoint: 'کراتین فسفات = باکتری انرژی لحظه‌ای عضله؛ سیستم ATP-PC.',
    related: { lesson: 'بیوانرژتیک عضله', wiki: 'Phosphocreatine' },
  },
];

/* فهرست مسابقهٔ نمونه برای صفحهٔ کارنامه (اسم دانشگاه‌ها در مقایسهٔ جامعه) — واقعی‌سازی UI */
export const COMMUNITY_META = {
  'exam-basic-national-01': { medianPercent: 41, averagePercent: 43, topPercent: 97 },
  'exam-physio-live-01': { medianPercent: 44, averagePercent: 46, topPercent: 95 },
  'exam-biochem-past-01': { medianPercent: 47, averagePercent: 49, topPercent: 96 },
  'exam-basic-mock-aug': { medianPercent: 38, averagePercent: 40, topPercent: 98 },
  'exam-first-term-01': { medianPercent: 45, averagePercent: 47, topPercent: 96 },
  'exam-daily-quiz': { medianPercent: 58, averagePercent: 61, topPercent: 100 },
};
