import { useMemo } from 'react';
import { GREEN_PATH_SECTIONS } from '../../../services/greenPath/greenPathConfig';
import { ArrowIcon, CalendarIcon, SectionHeader, formatDate, formatMinutes, formatWeekday, toFa } from './greenPathShared';
import { TaskCard } from './GreenPathCards';

function PeriodBadge({ status }) {
  const label = status === 'current' ? 'اکنون' : status === 'completed' ? 'پشت سر گذاشته شد' : 'پیش رو';
  return <span className={`gp-period-badge gp-period-badge--${status}`}>{label}</span>;
}

function SourceBars({ counts = {}, total = 0 }) {
  const entries = Object.entries(counts);
  if (!entries.length) return <div className="gp-period-empty">در این بازه Task ریز ساخته نشده است؛ تمرکز این بازه از فاز و هدف می‌آید.</div>;
  return <div className="gp-source-bars">{entries.map(([sourceId, count]) => { const source = GREEN_PATH_SECTIONS[sourceId] ?? { label: sourceId, accent: 'var(--green-ink)' }; return <div className="gp-source-bar" key={sourceId} style={{ '--gp-source-accent': source.accent }}><div><span>{source.label}</span><strong>{toFa(count)}</strong></div><span className="gp-source-bar__track"><i style={{ width: `${total ? (count / total) * 100 : 0}` }} /></span></div>; })}</div>;
}

export function GreenPathYearView({ snapshot, onOpenMonth, onOpenCalendar }) {
  const yearPlan = snapshot.yearPlan;
  const currentMonth = yearPlan.months.find((month) => month.status === 'current') ?? yearPlan.months[0];
  return <div className="gp-view gp-period-view"><section className="gp-period-hero"><div><span className="gp-eyebrow">YEAR PLAN</span><h1>نقشهٔ یک‌ساله</h1><p>سال به مرحله‌های قابل اجرا تقسیم شده؛ هر ماه یک تمرکز، هر هفته یک تعهد و هر روز یک قدم دارد.</p><div className="gp-period-hero__actions"><button type="button" className="gp-button gp-button--primary" onClick={() => onOpenMonth?.(currentMonth?.id)}>ماه جاری <ArrowIcon /></button><button type="button" className="gp-button gp-button--ghost" onClick={onOpenCalendar}>باز کردن تقویم</button></div></div><div className="gp-year-stats"><span><strong>{toFa(yearPlan.monthCount)}</strong><small>ماه برنامه</small></span><span><strong>{toFa(yearPlan.weekCount)}</strong><small>هفته برنامه</small></span><span><strong>{toFa(yearPlan.taskCount)}</strong><small>فعالیت قابل ردیابی</small></span></div></section><section className="gp-panel"><SectionHeader eyebrow="ANNUAL ARC" title="دوازده ماه، دوازده تصمیم" description="ماه‌ها بر اساس وضعیت هدف و فازهای Curriculum ساخته شده‌اند؛ بدون پرکردن تقویم با دادهٔ ساختگی." /><div className="gp-month-grid">{yearPlan.months.map((month) => <button type="button" className={`gp-month-card ${month.status === 'current' ? 'is-current' : ''}`} key={month.id} onClick={() => onOpenMonth?.(month.id)}><header><span>{toFa(month.index)}</span><PeriodBadge status={month.status} /></header><strong>{month.label}</strong><small>{month.phaseLabel}</small><div className="gp-month-card__line"><span>{toFa(month.taskCount)} فعالیت</span><span>{formatMinutes(month.plannedMinutes)}</span></div><span className="gp-progress"><i style={{ width: `${month.targetCoverage ?? Math.min(100, month.taskCount * 4)}%` }} /></span><em>{month.focus}</em></button>)}</div></section><section className="gp-panel"><SectionHeader eyebrow="ANNUAL SOURCES" title="سهم بخش‌های تپش در سال" description="تفکیک بخش‌ها در تمام سطوح حفظ می‌شود و رنگ هر منبع در تقویم هم همین است." /><SourceBars counts={yearPlan.months.reduce((all, month) => { Object.entries(month.sourceCounts ?? {}).forEach(([id, count]) => { all[id] = (all[id] ?? 0) + count; }); return all; }, {})} total={yearPlan.taskCount} /></section></div>;
}

export function GreenPathMonthView({ monthPlan, onBack, onOpenWeek, onOpenCalendar, onComplete, onFocus, onOpenResource, onReschedule }) {
  if (!monthPlan) return <div className="gp-view"><div className="gp-panel"><p>ماه پیدا نشد.</p><button type="button" className="gp-button gp-button--ghost" onClick={onBack}>بازگشت</button></div></div>;
  const weeks = monthPlan.weeks ?? [];
  return <div className="gp-view gp-period-view"><section className="gp-period-hero gp-period-hero--month"><div><button type="button" className="gp-back-button" onClick={onBack}><ArrowIcon direction="right" /> بازگشت به سال</button><span className="gp-eyebrow">MONTH PLAN · {toFa(monthPlan.index)}</span><h1>{monthPlan.label}</h1><p>{monthPlan.focus}</p><div className="gp-period-hero__actions"><button type="button" className="gp-button gp-button--primary" onClick={onOpenCalendar}><CalendarIcon className="gp-icon" /> تقویم این ماه</button></div></div><div className="gp-year-stats"><span><strong>{toFa(monthPlan.taskCount)}</strong><small>فعالیت</small></span><span><strong>{formatMinutes(monthPlan.plannedMinutes)}</strong><small>زمان برنامه</small></span><span><strong>{toFa(monthPlan.weeks.length)}</strong><small>هفته</small></span></div></section><section className="gp-panel"><SectionHeader eyebrow="MONTH FLOW" title="هفته‌های این ماه" description="هر هفته از همان Roadmap و ظرفیت ساخته شده و به Taskهایش وصل است." /><div className="gp-week-card-list">{weeks.map((week) => <button type="button" className={`gp-week-card ${week.status === 'current' ? 'is-current' : ''}`} key={week.id} onClick={() => onOpenWeek?.(week.id)}><header><div><strong>هفته {toFa(week.index)}</strong><small>{formatDate(week.startDate, { short: true })} تا {formatDate(week.endDate, { short: true })}</small></div><PeriodBadge status={week.status} /></header><p>{week.phaseLabel}</p><div className="gp-week-card__meta"><span>{toFa(week.taskCount)} فعالیت</span><span>{formatMinutes(week.plannedMinutes)}</span><span>{toFa(week.examIds.length)} آزمون/ددلاین</span></div><span className="gp-progress"><i style={{ width: `${week.targetCoverage ?? Math.min(100, week.taskCount * 5)}%` }} /></span></button>)}</div></section></div>;
}

export function GreenPathDayView({ snapshot, date, onBack, onComplete, onFocus, onOpenResource, onReschedule }) {
  const day = useMemo(() => snapshot.roadmap.byDate.find((item) => item.date === date) ?? null, [snapshot.roadmap.byDate, date]);
  const tasks = day?.tasks ?? [];
  const resourcesFor = (task) => snapshot.resources.filter((resource) => task.resourceIds?.includes(resource.id));
  return <div className="gp-view gp-period-view"><section className="gp-period-hero gp-period-hero--day"><div><button type="button" className="gp-back-button" onClick={onBack}><ArrowIcon direction="right" /> بازگشت به هفته</button><span className="gp-eyebrow">DAY PLAN</span><h1>{formatWeekday(date)}</h1><p>{formatDate(date)} · برنامهٔ واقعی همان روز، با امکان تکمیل و جابه‌جایی کنترل‌شده.</p></div><div className="gp-year-stats"><span><strong>{toFa(tasks.length)}</strong><small>فعالیت</small></span><span><strong>{formatMinutes(day?.plannedMinutes ?? 0)}</strong><small>زمان برنامه</small></span><span><strong>{toFa(day?.utilization ?? 0)}٪</strong><small>ظرفیت</small></span></div></section><section className="gp-panel"><SectionHeader eyebrow="TODAY" title="جزئیات روز" description="با انجام هر فعالیت، Progress و Roadmap بعدی دوباره محاسبه می‌شوند." />{tasks.length ? <div className="gp-task-list">{tasks.map((task) => <TaskCard key={task.id} task={task} resources={resourcesFor(task)} onComplete={onComplete} onFocus={onFocus} onOpenResource={onOpenResource} onReschedule={onReschedule} />)}</div> : <div className="gp-period-empty">برای این روز فعالیتی در افق فعلی برنامه ثبت نشده است.</div>}</section></div>;
}
