/*
 * رجیستری قرارداد ورودی مسیرهای نوشتن — فاز ۴.
 *
 * ⚠️ این فایل **تولیدشده** است: `node scripts/generate-route-contracts.mjs`.
 * دستی ویرایش نکن؛ با `npm run api:contract:check` کهنه‌بودنش سنجیده می‌شود.
 *
 * نقش آن در دروازه: هر مسیر نوشتن در سورس **باید** اینجا کلید داشته باشد.
 * مسیر نوشتن تازه بدون کلید ⇒ `api:contract:check` قرمز می‌شود. یعنی هیچ
 * endpoint جدیدی نمی‌تواند بدون قرارداد ورودی وارد main شود.
 *
 * انواع قرارداد:
 *   entity — اعتبارسنجی کامل با Schema مدل (`assertInputValid`).
 *   object — فقط «بدنه یک شیء سادهٔ JSON است» (دامنه Schema دار ندارد).
 *   none   — بدنهٔ JSON ندارد (آپلود جریانی / عملیات بدون payload).
 */

export const ROUTE_CONTRACTS = Object.freeze({
  'DELETE /api/admin/analytics/alerts/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/articles/:id': { kind: 'object', reason: 'دامنهٔ «articles» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'DELETE /api/admin/banners/:id': { kind: 'object', reason: 'دامنهٔ «banners» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'DELETE /api/admin/categories/:id': { kind: 'object', reason: 'دامنهٔ «categories» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'DELETE /api/admin/feedback/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/flashcards/:id': { kind: 'object', reason: 'دامنهٔ «flashcards» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'DELETE /api/admin/intl-courses/:id': { kind: 'object', reason: 'دامنهٔ «intl-courses» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'DELETE /api/admin/intl-providers/:id': { kind: 'object', reason: 'دامنهٔ «intl-providers» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'DELETE /api/admin/media/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/accounts/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/assets/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/campaigns/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/contents/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/inbox/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/mentions/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/metrics/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/platforms/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/tags/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/team/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/media/utm/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/micro/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/notes/:id': { kind: 'entity', entity: 'note', mode: 'update' },
  'DELETE /api/admin/pages/:id': { kind: 'object', reason: 'دامنهٔ «pages» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'DELETE /api/admin/publishing/channels/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'DELETE /api/admin/references/:id': { kind: 'object', reason: 'دامنهٔ «references» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'DELETE /api/admin/test-bank/:id': { kind: 'object', reason: 'دامنهٔ «test-bank» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'DELETE /api/admin/users/:id': { kind: 'object', reason: 'دامنهٔ «users» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'DELETE /api/exams/:slug/registration': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PATCH /api/users/me': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/analytics/alerts': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/analytics/reset': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/articles': { kind: 'object', reason: 'دامنهٔ «articles» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/articles/:id/status': { kind: 'object', reason: 'دامنهٔ «articles» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/auth/login': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/auth/logout': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/auth/password': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/banners': { kind: 'object', reason: 'دامنهٔ «banners» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/categories': { kind: 'object', reason: 'دامنهٔ «categories» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/feedback/:id/reply': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/feedback/:id/status': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/flashcards': { kind: 'object', reason: 'دامنهٔ «flashcards» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/intl-courses': { kind: 'object', reason: 'دامنهٔ «intl-courses» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/intl-courses/upload': { kind: 'object', reason: 'دامنهٔ «intl-courses» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/intl-providers': { kind: 'object', reason: 'دامنهٔ «intl-providers» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/media': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/accounts': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/accounts/:id/credentials': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/accounts/:id/sync': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/accounts/:id/test': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/accounts/import': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/accounts/sync': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/accounts/test': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/assets/:id/archive': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/campaigns': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/contents': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/contents/:id/approve': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/contents/:id/publish': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/contents/:id/retry': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/contents/:id/revision': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/contents/:id/schedule': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/contents/:id/status': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/contents/:id/submit': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/contents/preview': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/demo/clear': { kind: 'none', reason: 'بدنهٔ JSON ندارد (جریان/عملیات بدون payload)' },
  'POST /api/admin/media/demo/seed': { kind: 'none', reason: 'بدنهٔ JSON ندارد (جریان/عملیات بدون payload)' },
  'POST /api/admin/media/inbox': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/inbox/:id/assign': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/inbox/:id/reply': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/inbox/:id/status': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/mentions': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/metrics': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/notifications/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/notifications/read-all': { kind: 'none', reason: 'بدنهٔ JSON ندارد (جریان/عملیات بدون payload)' },
  'POST /api/admin/media/notifications/refresh': { kind: 'none', reason: 'بدنهٔ JSON ندارد (جریان/عملیات بدون payload)' },
  'POST /api/admin/media/platforms': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/queue/run': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/tags': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/team': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/utm': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/media/utm/preview': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/micro': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/micro/:id/status': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/notes': { kind: 'entity', entity: 'note', mode: 'update' },
  'POST /api/admin/notes/:id/items/:itemId/toggle': { kind: 'entity', entity: 'note', mode: 'update' },
  'POST /api/admin/notes/:id/pin': { kind: 'entity', entity: 'note', mode: 'update' },
  'POST /api/admin/pages': { kind: 'object', reason: 'دامنهٔ «pages» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/publishing/channels': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/publishing/channels/:id/test': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/publishing/channels/:id/token': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/publishing/preview': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/publishing/send': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/publishing/test': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/admin/references': { kind: 'object', reason: 'دامنهٔ «references» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/test-bank': { kind: 'object', reason: 'دامنهٔ «test-bank» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/admin/users': { kind: 'object', reason: 'دامنهٔ «users» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/attempts/:id/submit': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/exams/:slug/attempts': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/exams/:slug/registration': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/public/analytics/collect': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/public/feedback': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/public/feedback/replies/read': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/questions/:id/report': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/users/login': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/users/logout': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/users/register': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'POST /api/users/test-bank/answers': { kind: 'object', reason: 'دامنهٔ «test-bank» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'POST /api/users/test-bank/grade': { kind: 'object', reason: 'دامنهٔ «test-bank» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/admin/analytics/alerts/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/articles/:id': { kind: 'object', reason: 'دامنهٔ «articles» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/admin/banners/:id': { kind: 'object', reason: 'دامنهٔ «banners» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/admin/categories/:id': { kind: 'object', reason: 'دامنهٔ «categories» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/admin/comprehensive/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/flashcards/:id': { kind: 'object', reason: 'دامنهٔ «flashcards» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/admin/intl-courses/:id': { kind: 'object', reason: 'دامنهٔ «intl-courses» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/admin/intl-providers/:id': { kind: 'object', reason: 'دامنهٔ «intl-providers» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/admin/media/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/media/accounts/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/media/assets/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/media/campaigns/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/media/contents/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/media/mentions/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/media/tags/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/media/team/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/media/utm/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/micro/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/notes/:id': { kind: 'entity', entity: 'note', mode: 'update' },
  'PUT /api/admin/pages/:id': { kind: 'object', reason: 'دامنهٔ «pages» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/admin/publishing/channels/:id': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/references/:id': { kind: 'object', reason: 'دامنهٔ «references» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/admin/settings': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/admin/test-bank/:id': { kind: 'object', reason: 'دامنهٔ «test-bank» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/admin/users/:id': { kind: 'object', reason: 'دامنهٔ «users» Schema دارد ولی بدنهٔ سیم با شکل رکورد مدل یکی نیست؛ قرارداد سیم جدا لازم است' },
  'PUT /api/attempts/:id/answers': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
  'PUT /api/attempts/:id/progress': { kind: 'object', reason: 'دامنهٔ Schema دار ندارد؛ فقط ساختار بدنه سنجیده می‌شود' },
});

/** خلاصه — برای گزارش دروازه و تشخیص «بدهیِ باقی‌مانده». */
export const CONTRACT_SUMMARY = Object.freeze({
  total: 134,
  entity: 5,
  object: 125,
  none: 4,
});
